// ─── Extended County Intelligence Seed Data ───────────────────────────────────
// Real appeal strategies for 59 additional high-value counties beyond the top 25.
// Covers NJ, CT, NY, PA, MA, TX, CA, AZ, CO, NV, GA, NC, VA, MD, OH, MI, MN,
// WA, OR, IN regions.
//
// Run after seed-counties.ts and seed-top-counties.ts.
//
// Usage:
//   SUPABASE_URL=... SUPABASE_SERVICE_ROLE_KEY=... npx tsx scripts/seed-extended-counties.ts

interface CountyUpdate {
  county_fips: string;
  appeal_board_name: string;
  appeal_board_phone: string | null;
  portal_url: string | null;
  appeal_deadline_rule: string;
  accepts_online_filing: boolean;
  hearing_format: string | null;
  informal_review_available: boolean;
  informal_review_notes: string | null;
  filing_fee_cents: number;
  virtual_hearing_available: boolean;
  virtual_hearing_platform: string | null;
  pro_se_tips: string | null;
  notes: string | null;
  last_verified_date: string;
  verified_by: string;
}

const EXTENDED_COUNTIES: CountyUpdate[] = [
  // ═══════════════════════════════════════════════════════════════════════
  // NEW JERSEY — High-tax state, standardized Form A-1, njappealonline.com
  // ═══════════════════════════════════════════════════════════════════════
  {
    county_fips: '34003',
    appeal_board_name: 'Bergen County Board of Taxation',
    appeal_board_phone: '(201) 336-6300',
    portal_url: 'https://secure.njappealonline.com/',
    appeal_deadline_rule: 'April 1 or 45 days from assessment mailing, whichever is later. May 1 in revaluation years.',
    accepts_online_filing: true,
    hearing_format: 'in_person',
    informal_review_available: false,
    informal_review_notes: 'Contact local municipal assessor for informal discussion before filing.',
    filing_fee_cents: 0,
    virtual_hearing_available: false,
    virtual_hearing_platform: null,
    pro_se_tips: 'File Form A-1 with 3-5 comparable sales. Evidence must be submitted to all parties 7 days before hearing. Five-member board. Online filing via njappealonline.com auto-serves copies to assessor and clerk.',
    notes: 'NJ standardized process. Filing fee varies by assessed value. All property taxes must be current through Q1.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },
  {
    county_fips: '34013',
    appeal_board_name: 'Essex County Board of Taxation',
    appeal_board_phone: '(973) 395-8525',
    portal_url: 'https://www.essexcountynjtaxboard.org/',
    appeal_deadline_rule: 'April 1 or 45 days from bulk mailing, whichever is later',
    accepts_online_filing: true,
    hearing_format: 'in_person',
    informal_review_available: false,
    informal_review_notes: null,
    filing_fee_cents: 0,
    virtual_hearing_available: false,
    virtual_hearing_platform: null,
    pro_se_tips: 'Include 3-5 comparable properties. Must prove assessment is unreasonable vs market value. Submit copy to assessor and municipal clerk.',
    notes: 'No virtual hearings. Newark metro area — high volume of appeals.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },
  {
    county_fips: '34023',
    appeal_board_name: 'Middlesex County Board of Taxation',
    appeal_board_phone: null,
    portal_url: 'https://secure.njappealonline.com/',
    appeal_deadline_rule: 'April 1 or May 1 if revaluation year',
    accepts_online_filing: true,
    hearing_format: 'in_person',
    informal_review_available: false,
    informal_review_notes: null,
    filing_fee_cents: 0,
    virtual_hearing_available: false,
    virtual_hearing_platform: null,
    pro_se_tips: 'Payment of 1st quarter taxes required before appeal accepted. All hearings in-person only — board passed resolution against virtual hearings.',
    notes: 'Explicit no-virtual policy. Q1 tax payment required.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },
  {
    county_fips: '34017',
    appeal_board_name: 'Hudson County Board of Taxation',
    appeal_board_phone: null,
    portal_url: 'https://secure.njappealonline.com/',
    appeal_deadline_rule: 'April 1 or May 1 if revaluation year',
    accepts_online_filing: true,
    hearing_format: 'in_person',
    informal_review_available: false,
    informal_review_notes: null,
    filing_fee_cents: 0,
    virtual_hearing_available: false,
    virtual_hearing_platform: null,
    pro_se_tips: 'Prove assessed value unreasonable vs market standard. Include 3-5 comparable sales. Online filing automatically serves assessor and clerk. Strict deadline enforcement.',
    notes: 'Jersey City metro. Strict deadlines.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },
  {
    county_fips: '34025',
    appeal_board_name: 'Monmouth County Board of Taxation',
    appeal_board_phone: '(732) 431-7404',
    portal_url: 'https://secure.njappealonline.com/',
    appeal_deadline_rule: 'January 15 of current tax year',
    accepts_online_filing: true,
    hearing_format: 'both',
    informal_review_available: false,
    informal_review_notes: 'Can elect to proceed on submitted evidence without appearing at hearing.',
    filing_fee_cents: 0,
    virtual_hearing_available: true,
    virtual_hearing_platform: 'Zoom — select virtual option at time of filing',
    pro_se_tips: 'One of the few NJ counties with virtual hearing option. Select virtual or in-person when filing. Hearings held Jan 15–April 30.',
    notes: 'Early Jan 15 deadline (earlier than most NJ counties). Virtual option available.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },
  {
    county_fips: '34027',
    appeal_board_name: 'Morris County Board of Taxation',
    appeal_board_phone: '(973) 285-6707',
    portal_url: 'https://secure.njappealonline.com/',
    appeal_deadline_rule: 'April 1 or May 1 if revaluation year',
    accepts_online_filing: true,
    hearing_format: 'in_person',
    informal_review_available: false,
    informal_review_notes: null,
    filing_fee_cents: 0,
    virtual_hearing_available: false,
    virtual_hearing_platform: null,
    pro_se_tips: 'Evidence to all parties 7 days before hearing. Hearings conducted like a trial. 5-member commission. Comparable sales are the most important evidence. Hearings before end of June.',
    notes: 'Trial-like hearing format. Comparable sales critical.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },
  {
    county_fips: '34029',
    appeal_board_name: 'Ocean County Board of Taxation',
    appeal_board_phone: '(732) 929-2008',
    portal_url: 'https://secure.njappealonline.com/',
    appeal_deadline_rule: 'April 1 or May 1 if revaluation. December 1 for added assessments.',
    accepts_online_filing: true,
    hearing_format: 'in_person',
    informal_review_available: false,
    informal_review_notes: null,
    filing_fee_cents: 0,
    virtual_hearing_available: false,
    virtual_hearing_platform: null,
    pro_se_tips: 'File online at njappealonline.com — no additional mailings needed. Dec 1 deadline for added assessments is separate from regular April 1.',
    notes: 'Two separate deadlines: April 1 regular, Dec 1 added assessments.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },
  {
    county_fips: '34039',
    appeal_board_name: 'Union County Board of Taxation',
    appeal_board_phone: '(908) 527-4775',
    portal_url: 'https://secure.njappealonline.com/',
    appeal_deadline_rule: 'April 1 or May 1 if revaluation year',
    accepts_online_filing: true,
    hearing_format: 'in_person',
    informal_review_available: false,
    informal_review_notes: null,
    filing_fee_cents: 0,
    virtual_hearing_available: false,
    virtual_hearing_platform: null,
    pro_se_tips: '$5 convenience charge added for online filing. Filing fee waived for qualifying seniors/veterans. Online system auto-serves copies. All property taxes must be paid through Q1.',
    notes: '$5 online convenience fee. Senior/veteran fee waiver available.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },

  // ═══════════════════════════════════════════════════════════════════════
  // CONNECTICUT — No filing fees, February 20 deadline
  // ═══════════════════════════════════════════════════════════════════════
  {
    county_fips: '09001',
    appeal_board_name: 'Board of Assessment Appeals (municipality-level)',
    appeal_board_phone: null,
    portal_url: null,
    appeal_deadline_rule: 'February 20 (postmarks NOT accepted — must be received by this date)',
    accepts_online_filing: false,
    hearing_format: 'in_person',
    informal_review_available: false,
    informal_review_notes: 'Contact local assessor office before filing.',
    filing_fee_cents: 0,
    virtual_hearing_available: false,
    virtual_hearing_platform: null,
    pro_se_tips: 'POSTMARKS NOT ACCEPTED — hand-deliver or ensure receipt by Feb 20. Board not bound by strict rules of evidence. Bridgeport board meets only in March (real estate) and September (motor vehicle). Can appeal to Superior Court Tax & Administrative Appeals Session.',
    notes: 'Fairfield County includes Stamford, Bridgeport, Norwalk. Municipality-level boards.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },
  {
    county_fips: '09003',
    appeal_board_name: 'Board of Assessment Appeals (municipality-level)',
    appeal_board_phone: null,
    portal_url: null,
    appeal_deadline_rule: 'February 20 (varies by municipality — some March 20)',
    accepts_online_filing: false,
    hearing_format: 'in_person',
    informal_review_available: false,
    informal_review_notes: 'Include supporting documents with application if possible.',
    filing_fee_cents: 0,
    virtual_hearing_available: false,
    virtual_hearing_platform: null,
    pro_se_tips: 'Contact local tax assessor for specific deadline and procedures. Hearings typically March/April. BAA consists of local residents. Certified appraisal needed if appealing to superior court.',
    notes: 'Hartford County. Municipality-level boards with local resident members.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },

  // ═══════════════════════════════════════════════════════════════════════
  // NEW YORK (additional)
  // ═══════════════════════════════════════════════════════════════════════
  {
    county_fips: '36119',
    appeal_board_name: 'Board of Assessment Review (municipality-level)',
    appeal_board_phone: null,
    portal_url: 'https://www.tax.ny.gov/pit/property/contest/grievproced.htm',
    appeal_deadline_rule: 'Third Tuesday in June (most towns). Different for villages/cities.',
    accepts_online_filing: false,
    hearing_format: 'in_person',
    informal_review_available: true,
    informal_review_notes: 'BAR process at local level. Informal discussion with assessor standard practice.',
    filing_fee_cents: 0,
    virtual_hearing_available: true,
    virtual_hearing_platform: 'Zoom for SCAR proceedings',
    pro_se_tips: 'File Form RP-524 with local assessor. Different deadlines by municipality. SCAR filing is $30 with 2.99% credit card fee. Westchester has some of the highest property taxes in the nation — strong appeal potential.',
    notes: 'Westchester County — extremely high property taxes. SCAR available for owner-occupants.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },
  {
    county_fips: '36029',
    appeal_board_name: 'Erie County Real Property Tax Services / Board of Assessment Review',
    appeal_board_phone: '(716) 858-8333',
    portal_url: 'https://www3.erie.gov/ecrpts/',
    appeal_deadline_rule: 'Fourth Tuesday in May for most municipalities. Buffalo: December 1-31.',
    accepts_online_filing: false,
    hearing_format: 'in_person',
    informal_review_available: false,
    informal_review_notes: 'Contact local assessor directly.',
    filing_fee_cents: 0,
    virtual_hearing_available: false,
    virtual_hearing_platform: null,
    pro_se_tips: 'BUFFALO has completely different schedule (Dec 1-31 for BAR grievances). Erie County towns follow standard May schedule. SCAR and Article 7 Certiorari options for further appeal.',
    notes: 'Buffalo vs rest of Erie County have different schedules.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },
  {
    county_fips: '36055',
    appeal_board_name: 'Board of Assessment Review (Monroe County)',
    appeal_board_phone: '(585) 753-1125',
    portal_url: 'https://www.monroecounty.gov/property',
    appeal_deadline_rule: 'Third Tuesday in March (Rochester, 8 PM deadline). Fourth Tuesday in May for towns.',
    accepts_online_filing: false,
    hearing_format: 'in_person',
    informal_review_available: false,
    informal_review_notes: null,
    filing_fee_cents: 0,
    virtual_hearing_available: false,
    virtual_hearing_platform: null,
    pro_se_tips: 'HARD COPIES ONLY — no fax/email. Rochester requires original RP-524 by 8 PM on deadline day. SCAR or Article 7 for further appeal.',
    notes: 'Rochester has early March deadline (different from county towns in May). Hard copy only.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },

  // ═══════════════════════════════════════════════════════════════════════
  // PENNSYLVANIA (additional)
  // ═══════════════════════════════════════════════════════════════════════
  {
    county_fips: '42091',
    appeal_board_name: 'Montgomery County Board of Assessment Appeals',
    appeal_board_phone: '(610) 278-3761',
    portal_url: null,
    appeal_deadline_rule: 'August 1 of year prior to tax year',
    accepts_online_filing: true,
    hearing_format: 'in_person',
    informal_review_available: false,
    informal_review_notes: 'Possible informal discussion with assessor but not standard procedure.',
    filing_fee_cents: 5000,
    virtual_hearing_available: false,
    virtual_hearing_platform: null,
    pro_se_tips: 'Processing fee: Residential $50, Multi-family $100, Commercial/Industrial $200. Appeal hearings start May, must be heard by Oct 31. Forms available online.',
    notes: 'Filing fees vary by property type. Appeal year before tax year.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },
  {
    county_fips: '42029',
    appeal_board_name: 'Chester County Board of Assessment Appeals',
    appeal_board_phone: '(610) 344-6105',
    portal_url: 'https://www.chesco.org/255/Assessment-Appeals',
    appeal_deadline_rule: 'May 1 through first business day in August',
    accepts_online_filing: false,
    hearing_format: 'in_person',
    informal_review_available: false,
    informal_review_notes: 'Board reviews after notice of appeal filed.',
    filing_fee_cents: 15000,
    virtual_hearing_available: false,
    virtual_hearing_platform: null,
    pro_se_tips: 'Commercial/Industrial/Exemption processing fee $150 as of Jan 2026. Prepare documentation supporting your opinion of value. Board schedules hearings after filing.',
    notes: '$150 fee for commercial. May-August filing window.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },
  {
    county_fips: '42017',
    appeal_board_name: 'Bucks County Board of Assessment Appeals',
    appeal_board_phone: '(215) 348-6219',
    portal_url: 'https://www.buckscountyboa.org/',
    appeal_deadline_rule: 'August 1 for following year appeals',
    accepts_online_filing: false,
    hearing_format: 'in_person',
    informal_review_available: false,
    informal_review_notes: null,
    filing_fee_cents: 0,
    virtual_hearing_available: false,
    virtual_hearing_platform: null,
    pro_se_tips: 'No facsimiles accepted. Supporting info due 10 days before hearing. Board may hear all probative evidence. Attorney or authorized rep must attend unless waiver requested.',
    notes: 'No fax filing. 10-day evidence deadline before hearing.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },

  // ═══════════════════════════════════════════════════════════════════════
  // MASSACHUSETTS — Form 128 abatement process
  // ═══════════════════════════════════════════════════════════════════════
  {
    county_fips: '25017',
    appeal_board_name: 'Board of Assessors / Appellate Tax Board (municipality-level)',
    appeal_board_phone: null,
    portal_url: null,
    appeal_deadline_rule: 'February 1 or 30 days from 3rd quarter bill mailing, whichever is later',
    accepts_online_filing: false,
    hearing_format: 'in_person',
    informal_review_available: true,
    informal_review_notes: 'Submit Form 128 to local assessors for initial abatement review. This IS the informal step.',
    filing_fee_cents: 1000,
    virtual_hearing_available: false,
    virtual_hearing_platform: null,
    pro_se_tips: 'File Form 128 Application for Abatement with your local assessor first — this is mandatory. Must respond to info requests within 30 days or lose appeal rights. 3 months to appeal to Appellate Tax Board from denial.',
    notes: 'Middlesex County (Cambridge). Form 128 abatement mandatory first step. $10+ filing fee scales with value.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },
  {
    county_fips: '25021',
    appeal_board_name: 'Board of Assessors / Appellate Tax Board (municipality-level)',
    appeal_board_phone: null,
    portal_url: null,
    appeal_deadline_rule: 'February 1 or 30 days from bill mailing, whichever is later',
    accepts_online_filing: false,
    hearing_format: 'in_person',
    informal_review_available: true,
    informal_review_notes: 'File Form 128 abatement application with local assessor first — mandatory step.',
    filing_fee_cents: 1000,
    virtual_hearing_available: false,
    virtual_hearing_platform: null,
    pro_se_tips: '20 municipalities with own assessors — contact YOUR local town assessor directly. Form 128 is mandatory first step. 3 months to Appellate Tax Board from abatement denial.',
    notes: 'Norfolk County. 20 municipalities each with own assessor.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },
  {
    county_fips: '25027',
    appeal_board_name: 'City of Worcester Assessor / Appellate Tax Board',
    appeal_board_phone: null,
    portal_url: 'https://www.worcesterma.gov/finance/taxes-assessments/',
    appeal_deadline_rule: '30 days from date actual tax bill issued',
    accepts_online_filing: true,
    hearing_format: 'in_person',
    informal_review_available: true,
    informal_review_notes: 'Initial abatement application to local assessor is the informal step.',
    filing_fee_cents: 1000,
    virtual_hearing_available: false,
    virtual_hearing_platform: null,
    pro_se_tips: 'Online submission through City of Worcester portal. Must provide all requested info within 30 days — failure results in automatic denial with no extension possible. City Hall Room 209 for in-person.',
    notes: 'Worcester County. Online filing available through city portal.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },

  // ═══════════════════════════════════════════════════════════════════════
  // TEXAS (additional) — All May 15 deadline, free, online, informal available
  // ═══════════════════════════════════════════════════════════════════════
  {
    county_fips: '48085',
    appeal_board_name: 'Collin Central Appraisal District — Appraisal Review Board',
    appeal_board_phone: '(469) 742-9200',
    portal_url: 'https://collinarb.org/',
    appeal_deadline_rule: 'May 15 or 30 days after Notice mailed, whichever is later',
    accepts_online_filing: true,
    hearing_format: 'both',
    informal_review_available: true,
    informal_review_notes: 'Informal conference with appraiser before ARB hearing. 10-20 minute informal hearings. Most protests resolved here.',
    filing_fee_cents: 0,
    virtual_hearing_available: true,
    virtual_hearing_platform: 'Phone or video conference — request when filing',
    pro_se_tips: 'eFile available with PIN from notice. Collect comparable sales data. Informal hearings 10-20 minutes — most cases resolve here without formal ARB.',
    notes: 'Plano/McKinney area. eFile with PIN.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },
  {
    county_fips: '48121',
    appeal_board_name: 'Denton Central Appraisal District — Appraisal Review Board',
    appeal_board_phone: null,
    portal_url: 'https://www.dentoncad.com/appeals',
    appeal_deadline_rule: 'May 15 or 30 days after Notice mailed, whichever is later',
    accepts_online_filing: true,
    hearing_format: 'both',
    informal_review_available: true,
    informal_review_notes: 'One-on-one discussion with appraiser. Affidavit option available — can submit evidence without attending.',
    filing_fee_cents: 0,
    virtual_hearing_available: true,
    virtual_hearing_platform: 'Phone or video conference',
    pro_se_tips: 'Present evidence at informal level first — most protests resolved informally. Can attend by affidavit if you can\'t be there in person.',
    notes: 'Affidavit option unique to Denton — submit evidence without attending.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },
  {
    county_fips: '48157',
    appeal_board_name: 'Fort Bend Central Appraisal District — Appraisal Review Board',
    appeal_board_phone: null,
    portal_url: 'https://www.fbcad.org/appeals/',
    appeal_deadline_rule: 'May 15 or 30 days after Notice mailed, whichever is later',
    accepts_online_filing: true,
    hearing_format: 'both',
    informal_review_available: true,
    informal_review_notes: 'Informal conferences conducted remotely with appraiser.',
    filing_fee_cents: 0,
    virtual_hearing_available: true,
    virtual_hearing_platform: 'Phone or video conference',
    pro_se_tips: 'No filing fee. Informal conferences are remote. Late protests accepted if good cause shown before approval of records. Collect comparable sales data.',
    notes: 'Sugar Land area. Remote informal conferences. Late protests possible with good cause.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },
  {
    county_fips: '48491',
    appeal_board_name: 'Williamson Central Appraisal District — Appraisal Review Board',
    appeal_board_phone: '(512) 930-3787',
    portal_url: 'https://www.wcad.org/appeal/',
    appeal_deadline_rule: 'May 15 or 30 days after Notice mailed, whichever is later',
    accepts_online_filing: true,
    hearing_format: 'both',
    informal_review_available: true,
    informal_review_notes: 'Informal meeting with WCAD appraiser to discuss evidence and negotiate value.',
    filing_fee_cents: 0,
    virtual_hearing_available: true,
    virtual_hearing_platform: 'RingCentral video platform',
    pro_se_tips: '15-minute informal hearings. Present comparable sales evidence. Witness testimony allowed. Online calendar scheduling available.',
    notes: 'Round Rock area. Uses RingCentral for virtual hearings — unique platform.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },
  {
    county_fips: '48141',
    appeal_board_name: 'El Paso Central Appraisal District — Appraisal Review Board',
    appeal_board_phone: '(915) 780-2123',
    portal_url: 'https://epcad.org/OnlineServices/ProtestPortal',
    appeal_deadline_rule: 'May 15 or 30 days after Notice mailed, whichever is later',
    accepts_online_filing: true,
    hearing_format: 'both',
    informal_review_available: true,
    informal_review_notes: 'Informal review available — contact EPCAD.',
    filing_fee_cents: 0,
    virtual_hearing_available: true,
    virtual_hearing_platform: null,
    pro_se_tips: 'Online portal and mail filing accepted. Binding arbitration available after ARB decision.',
    notes: 'Binding arbitration option available post-ARB.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },
  {
    county_fips: '48339',
    appeal_board_name: 'Montgomery Central Appraisal District — Appraisal Review Board',
    appeal_board_phone: '(936) 756-3354',
    portal_url: 'https://mcad-tx.org/the-protest-process/',
    appeal_deadline_rule: 'May 15 or 30 days after Notice mailed, whichever is later',
    accepts_online_filing: true,
    hearing_format: 'both',
    informal_review_available: true,
    informal_review_notes: 'Informal hearing with appraiser — most protests resolved at this stage.',
    filing_fee_cents: 0,
    virtual_hearing_available: true,
    virtual_hearing_platform: 'Video conference',
    pro_se_tips: 'File through online portal (24/7). Informal hearings resolve most cases. Hearings at 109 Gladstell Street, Conroe.',
    notes: 'Conroe/Woodlands area. 24/7 online protest system.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },

  // ═══════════════════════════════════════════════════════════════════════
  // CALIFORNIA (additional) — July 2 window, strict, mostly paper filing
  // ═══════════════════════════════════════════════════════════════════════
  {
    county_fips: '06073',
    appeal_board_name: 'San Diego County Assessment Appeals Board',
    appeal_board_phone: '(619) 531-5777',
    portal_url: 'https://www.sandiegocounty.gov/content/sdc/cob/aab.html',
    appeal_deadline_rule: 'July 2 through December 1. Supplemental assessments: 60 days from notice.',
    accepts_online_filing: false,
    hearing_format: 'in_person',
    informal_review_available: false,
    informal_review_notes: null,
    filing_fee_cents: 0,
    virtual_hearing_available: false,
    virtual_hearing_platform: null,
    pro_se_tips: 'ORIGINAL SIGNATURE REQUIRED — mail or in-person filing only, no online filing. Missing deadline = complete loss of recourse for entire year. No extensions.',
    notes: 'Paper filing only with original signature. Phone dial-in for listening only.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },
  {
    county_fips: '06059',
    appeal_board_name: 'Orange County Assessment Appeals Board',
    appeal_board_phone: '(714) 834-2331',
    portal_url: 'https://assessmentappeals.ocgov.com/',
    appeal_deadline_rule: 'July 2 through December 2. Supplemental: 60 days from notice.',
    accepts_online_filing: true,
    hearing_format: 'both',
    informal_review_available: false,
    informal_review_notes: null,
    filing_fee_cents: 0,
    virtual_hearing_available: false,
    virtual_hearing_platform: null,
    pro_se_tips: 'Online filing available. Can choose Hearing Officer (1 person, faster, more informal) OR 3-member Board. Hearing Officer recommended for simpler cases.',
    notes: 'One of few CA counties with online filing. Hearing Officer option available.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },
  {
    county_fips: '06065',
    appeal_board_name: 'Riverside County Assessment Appeals Board',
    appeal_board_phone: '(951) 955-1069',
    portal_url: 'https://aao.countyofriverside.us',
    appeal_deadline_rule: 'July 2 through December 1. Supplemental: 60 days from notice.',
    accepts_online_filing: true,
    hearing_format: 'in_person',
    informal_review_available: false,
    informal_review_notes: null,
    filing_fee_cents: 0,
    virtual_hearing_available: false,
    virtual_hearing_platform: null,
    pro_se_tips: 'Form BOE-305-AH required. Appeals board is independent from Assessor. Board determines fair market value based on evidence presented.',
    notes: 'Board independent from Assessor. BOE-305-AH form required.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },
  {
    county_fips: '06071',
    appeal_board_name: 'San Bernardino County Assessment Appeals Board',
    appeal_board_phone: '(909) 387-4413',
    portal_url: 'https://assessmentappeals.cob.sbcounty.gov/',
    appeal_deadline_rule: 'July 2 through September 15 or December 1 (depending on assessment notice mailing date)',
    accepts_online_filing: false,
    hearing_format: 'both',
    informal_review_available: false,
    informal_review_notes: null,
    filing_fee_cents: 4500,
    virtual_hearing_available: false,
    virtual_hearing_platform: null,
    pro_se_tips: '$45 NON-REFUNDABLE fee required. Hearing Officer option for residential or properties under $500K. At least 45 days notice before hearing.',
    notes: '$45 non-refundable processing fee. Hearing Officer option for smaller properties.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },
  {
    county_fips: '06067',
    appeal_board_name: 'Sacramento County Assessment Appeals Board',
    appeal_board_phone: '(916) 874-8174',
    portal_url: 'https://assessor.saccounty.gov/Pages/AssessmentAppeals.aspx',
    appeal_deadline_rule: 'July 2 through December 1. Prop 8 decline-in-value review also available July 1–Dec 31.',
    accepts_online_filing: false,
    hearing_format: 'in_person',
    informal_review_available: true,
    informal_review_notes: 'Prop 8 informal review available at no charge between July 1 and December 31. Assessor staff can discuss valuation.',
    filing_fee_cents: 3000,
    virtual_hearing_available: false,
    virtual_hearing_platform: null,
    pro_se_tips: 'PAPER ONLY with original blue-ink signature. No extensions or grace periods. Prop 8 decline-in-value reviews are FREE and useful for market decline disputes. Missing deadline = complete loss of recourse.',
    notes: '$30 fee. Blue-ink original signature required. Prop 8 review is free alternative.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },
  {
    county_fips: '06085',
    appeal_board_name: 'Santa Clara County Assessment Appeals Board',
    appeal_board_phone: '(408) 299-5088',
    portal_url: 'https://cob.santaclaracounty.gov/appeal-your-property-taxes',
    appeal_deadline_rule: 'July 2 through September 15. Supplemental: 60 days from notice.',
    accepts_online_filing: true,
    hearing_format: 'both',
    informal_review_available: true,
    informal_review_notes: 'Can submit factual information to Assessor by August 1 before filing formal appeal.',
    filing_fee_cents: 29000,
    virtual_hearing_available: false,
    virtual_hearing_platform: null,
    pro_se_tips: 'FEES: Residential $290/parcel, Commercial $675/parcel. Three board types: Value Officer, Legal Officer, full Board. 21 days notice required for postponement.',
    notes: 'San Jose. Highest CA filing fees. Multiple board types available.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },
  {
    county_fips: '06001',
    appeal_board_name: 'Alameda County Assessment Appeals Board',
    appeal_board_phone: '(510) 272-6352',
    portal_url: 'https://aab.alamedacountyca.gov/',
    appeal_deadline_rule: 'July 2 through September 15. Supplemental: 60 days from notice.',
    accepts_online_filing: false,
    hearing_format: 'in_person',
    informal_review_available: true,
    informal_review_notes: 'Informal "Decline in Market Value" request available at no cost with certified appraiser.',
    filing_fee_cents: 5000,
    virtual_hearing_available: false,
    virtual_hearing_platform: null,
    pro_se_tips: '$50 filing fee — certified check or money order ONLY. Mail or in-person filing. 45 days notice before hearing. Free informal decline-in-value request available.',
    notes: 'Oakland area. $50 fee, check/money order only. Free informal option.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },
  {
    county_fips: '06013',
    appeal_board_name: 'Contra Costa County Assessment Appeals Board',
    appeal_board_phone: '(925) 655-2008',
    portal_url: 'https://www.contracosta.ca.gov/2924/Assessment-Appeals',
    appeal_deadline_rule: 'July 2 through November 30. Supplemental: 60 days from notice.',
    accepts_online_filing: false,
    hearing_format: 'in_person',
    informal_review_available: false,
    informal_review_notes: null,
    filing_fee_cents: 4000,
    virtual_hearing_available: false,
    virtual_hearing_platform: null,
    pro_se_tips: '$40 application fee. BOE-305-AH form required. Hearings Thursdays at 9am. MUST return Notice of Intent to Appear or hearing is cancelled. 1025 Escobar St, Martinez.',
    notes: '$40 fee. Must return Intent to Appear or hearing cancelled. Thursdays 9am.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },

  // ═══════════════════════════════════════════════════════════════════════
  // ARIZONA, COLORADO, NEVADA (additional)
  // ═══════════════════════════════════════════════════════════════════════
  {
    county_fips: '04019',
    appeal_board_name: 'Pima County Assessor / Arizona State Board of Equalization',
    appeal_board_phone: '(520) 724-8630',
    portal_url: 'https://www.asr.pima.gov/appeal',
    appeal_deadline_rule: '60 days from Notice of Valuation. State Board: 25 days from Assessor decision.',
    accepts_online_filing: true,
    hearing_format: 'both',
    informal_review_available: true,
    informal_review_notes: 'Informal petition with County Assessor — can discuss valuation with appraiser.',
    filing_fee_cents: 0,
    virtual_hearing_available: true,
    virtual_hearing_platform: null,
    pro_se_tips: 'Petition within 60 days of Notice. State Board within 25 days of Assessor decision. Can designate agent/representative. Tax Court option within 60 days of final decision as alternative to State Board.',
    notes: 'Tucson. Two-tier: Assessor → State Board. Tax Court as alternative path.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },
  {
    county_fips: '08031',
    appeal_board_name: 'Denver County Board of Equalization',
    appeal_board_phone: '(720) 913-4162',
    portal_url: 'https://denvergov.org/assessor',
    appeal_deadline_rule: 'File with Assessor by June 1. CBOE appeal within 30 days of Assessor decision.',
    accepts_online_filing: true,
    hearing_format: 'both',
    informal_review_available: false,
    informal_review_notes: null,
    filing_fee_cents: 0,
    virtual_hearing_available: true,
    virtual_hearing_platform: 'Secure web portal with email notifications',
    pro_se_tips: 'Three-tier: Assessor → CBOE → Board of Assessment Appeals. Must file with Assessor FIRST. Online system for filing and document management. Statutory appeal window typically 1-3 months.',
    notes: 'Denver. Three-tier system. Portal-based filing.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },
  {
    county_fips: '08005',
    appeal_board_name: 'Arapahoe County Board of Equalization',
    appeal_board_phone: '(303) 795-4600',
    portal_url: 'https://www.arapahoeco.gov/your_county/county_departments/assessor/appeals/',
    appeal_deadline_rule: 'May 1 through June 9 (Assessor). CBOE deadline: September 15.',
    accepts_online_filing: true,
    hearing_format: 'both',
    informal_review_available: false,
    informal_review_notes: null,
    filing_fee_cents: 0,
    virtual_hearing_available: true,
    virtual_hearing_platform: null,
    pro_se_tips: 'Schedule appointment by May 23. Provide evidence of valuation error. Written appeal to CBOE after Assessor decision. Two office locations: Littleton and Aurora. Binding arbitration option available. Email appeals@arapahoeco.com for CBOE.',
    notes: 'Two offices (Littleton/Aurora). Binding arbitration available.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },
  {
    county_fips: '08035',
    appeal_board_name: 'Douglas County Board of Equalization',
    appeal_board_phone: '(303) 660-7450',
    portal_url: 'https://appeals.spatialest.com/co-douglas',
    appeal_deadline_rule: 'May 1 through June 8 (Assessor). CBOE deadline: September 15.',
    accepts_online_filing: true,
    hearing_format: 'both',
    informal_review_available: false,
    informal_review_notes: null,
    filing_fee_cents: 0,
    virtual_hearing_available: true,
    virtual_hearing_platform: 'Secure web portal',
    pro_se_tips: 'County Commissioners serve as CBOE. Hearing officers make recommendations. Board of Assessment Appeals (BAA) portal for electronic filing. Binding arbitration also available.',
    notes: 'Commissioners = CBOE. Spatialest portal for appeals.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },
  {
    county_fips: '32031',
    appeal_board_name: 'Washoe County Board of Equalization',
    appeal_board_phone: '(775) 328-2233',
    portal_url: 'https://www.washoecounty.gov/assessor/real_property/appeal.php',
    appeal_deadline_rule: 'January 15 of year following assessment. No extensions.',
    accepts_online_filing: true,
    hearing_format: 'both',
    informal_review_available: false,
    informal_review_notes: 'Discuss with appraiser before filing formal appeal — highly recommended.',
    filing_fee_cents: 0,
    virtual_hearing_available: false,
    virtual_hearing_platform: null,
    pro_se_tips: 'Burden of proof is ON THE TAXPAYER to show valuation error. Appeal form from State Department of Taxation. No exceptions or extensions to January 15 deadline. Five-member board appointed by Commission Chairman. Talk to appraiser first.',
    notes: 'Reno. Taxpayer bears burden of proof. January 15 absolute deadline.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },

  // ═══════════════════════════════════════════════════════════════════════
  // GEORGIA (additional)
  // ═══════════════════════════════════════════════════════════════════════
  {
    county_fips: '13135',
    appeal_board_name: 'Gwinnett County Board of Equalization',
    appeal_board_phone: '(770) 822-7200',
    portal_url: 'https://www.gwinnettcounty.com/departments/financialservices/taxassessorsoffice/propertyappeals',
    appeal_deadline_rule: '45 days from notice date',
    accepts_online_filing: true,
    hearing_format: 'both',
    informal_review_available: false,
    informal_review_notes: 'Contact assessor informally but no formal process.',
    filing_fee_cents: 0,
    virtual_hearing_available: true,
    virtual_hearing_platform: 'WebEx',
    pro_se_tips: 'Gather comparable sales from 6-12 months prior to Jan 1. Recent appraisal within 9 months. Submit evidence 7 days before hearing. Can use agent/attorney/appraiser. Board is 3 citizen members.',
    notes: 'PT311A form or online letter. WebEx hearings available.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },
  {
    county_fips: '13089',
    appeal_board_name: 'DeKalb County Board of Equalization',
    appeal_board_phone: '(404) 371-0841',
    portal_url: 'https://www.dekalbcountyga.gov/property-appraisal/appeal-process',
    appeal_deadline_rule: '45 days from notice date',
    accepts_online_filing: false,
    hearing_format: 'in_person',
    informal_review_available: false,
    informal_review_notes: null,
    filing_fee_cents: 0,
    virtual_hearing_available: false,
    virtual_hearing_platform: null,
    pro_se_tips: 'Email/fax NOT accepted — hand-deliver or postmark by deadline. Board has 90 days to notify decision. During appeal: temporary value is lesser of last year or 85% of current assessment.',
    notes: 'Atlanta east. No email/fax. 85% temp value during appeal.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },
  {
    county_fips: '13067',
    appeal_board_name: 'Cobb County Board of Equalization',
    appeal_board_phone: '(770) 528-3100',
    portal_url: 'https://assessor.cobbcounty.gov/appeals/',
    appeal_deadline_rule: '45 days from mailing date',
    accepts_online_filing: false,
    hearing_format: 'both',
    informal_review_available: false,
    informal_review_notes: null,
    filing_fee_cents: 0,
    virtual_hearing_available: false,
    virtual_hearing_platform: null,
    pro_se_tips: 'Three appeal options: Board of Equalization (free), Arbitration (requires certified appraiser, costlier but faster), or Hearing Officer. Write letter with property address and parcel ID explaining disagreement.',
    notes: 'Marietta. Three appeal paths: BOE, Arbitration, Hearing Officer.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },

  // ═══════════════════════════════════════════════════════════════════════
  // NORTH CAROLINA
  // ═══════════════════════════════════════════════════════════════════════
  {
    county_fips: '37183',
    appeal_board_name: 'Wake County Board of Equalization and Review',
    appeal_board_phone: '(919) 857-3800',
    portal_url: 'https://services.wake.gov/TaxPortal/FAQ',
    appeal_deadline_rule: 'March 2 through May 15 (varies by year)',
    accepts_online_filing: true,
    hearing_format: 'in_person',
    informal_review_available: true,
    informal_review_notes: 'Informal appeal available — office reviews and decides. Contact (919) 856-5400 or email realproperty@wake.gov.',
    filing_fee_cents: 0,
    virtual_hearing_available: false,
    virtual_hearing_platform: null,
    pro_se_tips: 'File online at Tax Portal. Comparable sales, professional appraisal, photos. Personal appearance not required. BOER has 30 days to mail decision after hearing. Hearings at Wake County Commons Building.',
    notes: 'Raleigh. Informal review resolves many cases. Personal appearance not required.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },
  {
    county_fips: '37119',
    appeal_board_name: 'Mecklenburg County Board of Equalization and Review',
    appeal_board_phone: '(980) 314-4226',
    portal_url: 'https://cao.mecknc.gov/appeals',
    appeal_deadline_rule: 'By May 4 (adjournment date, varies by year)',
    accepts_online_filing: true,
    hearing_format: 'in_person',
    informal_review_available: true,
    informal_review_notes: 'Informal review available online — homeowner and assessor review valuation together without formal filing.',
    filing_fee_cents: 0,
    virtual_hearing_available: false,
    virtual_hearing_platform: null,
    pro_se_tips: 'Try informal review online first — assessor discusses valuation with you. Formal appeal form available online or mail/in-person. No attorney required. Personal appearance not required.',
    notes: 'Charlotte. Online informal review unique — try it first.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },

  // ═══════════════════════════════════════════════════════════════════════
  // VIRGINIA / MARYLAND
  // ═══════════════════════════════════════════════════════════════════════
  {
    county_fips: '51059',
    appeal_board_name: 'Fairfax County Board of Equalization',
    appeal_board_phone: '(703) 324-4891',
    portal_url: 'https://www.fairfaxcounty.gov/boe/appeal-application',
    appeal_deadline_rule: 'June 1 annually',
    accepts_online_filing: true,
    hearing_format: 'in_person',
    informal_review_available: false,
    informal_review_notes: null,
    filing_fee_cents: 0,
    virtual_hearing_available: false,
    virtual_hearing_platform: null,
    pro_se_tips: 'Show fair market value, lack of uniformity, or property description errors. Burden is on YOU to prove erroneous assessment. Online application for residential only. Board meets Mon/Thu 7pm, Wed 9am, June–December.',
    notes: 'DC suburb. Online for residential only. Meetings June-December.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },
  {
    county_fips: '24033',
    appeal_board_name: 'Property Tax Assessment Appeals Board (PTAAB)',
    appeal_board_phone: '(301) 952-2500',
    portal_url: 'https://assessmentappeals.dat.maryland.gov/',
    appeal_deadline_rule: '45 days from notice. First appeal to SDAT (no fee), then PTAAB (no fee).',
    accepts_online_filing: true,
    hearing_format: 'both',
    informal_review_available: false,
    informal_review_notes: 'SDAT is the first level — functions as initial review.',
    filing_fee_cents: 0,
    virtual_hearing_available: true,
    virtual_hearing_platform: 'Google Meet or phone',
    pro_se_tips: 'Compare properties similar in size/age/location. Use sales 6-12 months from assessment date. Provide 4 copies for PTAAB hearing. 15-day notice for comparables list. Three hearing options: written, phone, or video (Google Meet).',
    notes: "Prince George's County. DC suburb. Two free levels: SDAT → PTAAB. Tax Court third stage.",
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },
  {
    county_fips: '24031',
    appeal_board_name: 'Property Tax Assessment Appeals Board (PTAAB)',
    appeal_board_phone: '(301) 279-8333',
    portal_url: 'https://assessmentappeals.dat.maryland.gov/',
    appeal_deadline_rule: '45 days from notice. SDAT first, then PTAAB.',
    accepts_online_filing: true,
    hearing_format: 'both',
    informal_review_available: false,
    informal_review_notes: null,
    filing_fee_cents: 0,
    virtual_hearing_available: true,
    virtual_hearing_platform: 'Google Meet or phone',
    pro_se_tips: 'Comparable sales similar in design/condition/location/quality. 15-day notice for comparables. Provide appraisal 10 days before hearing. Three options: written, phone, video.',
    notes: 'Montgomery County MD. DC suburb. 51 Monroe St Room 201, Rockville.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },
  {
    county_fips: '24005',
    appeal_board_name: 'Property Tax Assessment Appeals Board (PTAAB)',
    appeal_board_phone: '(410) 321-3675',
    portal_url: 'https://assessmentappeals.dat.maryland.gov/',
    appeal_deadline_rule: '45 days from notice. SDAT first, then PTAAB.',
    accepts_online_filing: true,
    hearing_format: 'both',
    informal_review_available: false,
    informal_review_notes: null,
    filing_fee_cents: 0,
    virtual_hearing_available: true,
    virtual_hearing_platform: 'Google Meet or phone',
    pro_se_tips: 'Use sales closest to assessment date. Avoid comparing past values, tax amounts, or percent increases — boards reject those arguments. Three hearing formats available.',
    notes: 'Baltimore County. Hampton Plaza, 300 E Joppa Rd Suite 404, Towson.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },
  {
    county_fips: '24003',
    appeal_board_name: 'Property Tax Assessment Appeals Board (PTAAB)',
    appeal_board_phone: '(410) 974-5709',
    portal_url: 'https://assessmentappeals.dat.maryland.gov/',
    appeal_deadline_rule: '45 days from notice. SDAT first, then PTAAB.',
    accepts_online_filing: true,
    hearing_format: 'both',
    informal_review_available: false,
    informal_review_notes: null,
    filing_fee_cents: 0,
    virtual_hearing_available: true,
    virtual_hearing_platform: 'Google Meet or phone',
    pro_se_tips: 'Comparable sales closest to Jan 1. Provide 4 copies for PTAAB. Appraisal must be submitted 10 days before hearing. No fees at either level.',
    notes: 'Anne Arundel (Annapolis). P.O. Box 2700, Annapolis.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },

  // ═══════════════════════════════════════════════════════════════════════
  // OHIO / MICHIGAN / MINNESOTA (additional)
  // ═══════════════════════════════════════════════════════════════════════
  {
    county_fips: '39061',
    appeal_board_name: 'Hamilton County Board of Revision',
    appeal_board_phone: '(513) 946-4000',
    portal_url: 'https://www.hamiltoncountyauditor.org/bor.asp',
    appeal_deadline_rule: 'January 1 through March 31 (must be postmarked)',
    accepts_online_filing: false,
    hearing_format: 'both',
    informal_review_available: false,
    informal_review_notes: null,
    filing_fee_cents: 0,
    virtual_hearing_available: true,
    virtual_hearing_platform: 'Virtual or in-person hearings available',
    pro_se_tips: 'File DTE1 form. Recent appraisal as of Jan 1. Photos of damage. 5-day evidence submission deadline before hearing. 6-8 weeks for decision.',
    notes: 'Cincinnati. 138 East Court St Room 304. Virtual hearings available.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },
  {
    county_fips: '39153',
    appeal_board_name: 'Summit County Board of Revision',
    appeal_board_phone: '(330) 926-2559',
    portal_url: 'https://fiscaloffice.summitoh.net/index.php/board-of-revision-complaint',
    appeal_deadline_rule: 'January 1 through March 31',
    accepts_online_filing: true,
    hearing_format: 'in_person',
    informal_review_available: false,
    informal_review_notes: null,
    filing_fee_cents: 0,
    virtual_hearing_available: false,
    virtual_hearing_platform: null,
    pro_se_tips: 'SmartFile online portal available. File DTE1 form. Appraisal as of Jan 1 lien date. Submit evidence 5 days before hearing. Board hears valuation only — not tax complaints.',
    notes: 'Akron. SmartFile portal. 1180 S Main St Suite 250.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },
  {
    county_fips: '26125',
    appeal_board_name: 'Oakland County Board of Review / Michigan Tax Tribunal',
    appeal_board_phone: '(248) 858-0740',
    portal_url: 'https://bsaonline.com/?uid=525',
    appeal_deadline_rule: 'Local Board of Review in March (MANDATORY). Then Tax Tribunal by July 31 (residential) or May 31 (commercial).',
    accepts_online_filing: false,
    hearing_format: 'in_person',
    informal_review_available: false,
    informal_review_notes: null,
    filing_fee_cents: 0,
    virtual_hearing_available: false,
    virtual_hearing_platform: null,
    pro_se_tips: 'MUST protest Board of Review first for residential — no exceptions. Then Tax Tribunal by July 31. Comparable sales data essential. Small Claims Division available at Tribunal.',
    notes: 'Detroit suburbs. March BOR mandatory → July 31 Tribunal.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },
  {
    county_fips: '26099',
    appeal_board_name: 'Macomb County Board of Review / Michigan Tax Tribunal',
    appeal_board_phone: null,
    portal_url: 'https://www.macomb-mi.gov/161/Board-of-Review',
    appeal_deadline_rule: 'Local Board of Review in March (MANDATORY). Then Tax Tribunal by July 31 (residential) or May 31 (commercial).',
    accepts_online_filing: false,
    hearing_format: 'in_person',
    informal_review_available: false,
    informal_review_notes: null,
    filing_fee_cents: 0,
    virtual_hearing_available: false,
    virtual_hearing_platform: null,
    pro_se_tips: 'Must appear in person or by agent. Complete Board of Review Petition (L-4035). Bring 3 copies of all evidence. Non-residents may appeal by letter with form. Evidence copies not returned.',
    notes: 'Detroit suburbs. L-4035 form. Appointment required. 3 copies of evidence.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },
  {
    county_fips: '27123',
    appeal_board_name: 'Ramsey County Board of Equalization / Minnesota Tax Court',
    appeal_board_phone: '(651) 266-2131',
    portal_url: 'https://www.ramseycountymn.gov/residents/property-home/taxes-values/property-value-assessment/appealing-your-value',
    appeal_deadline_rule: 'Local Board meets Jan-April. Tax Court: April 30 absolute deadline.',
    accepts_online_filing: false,
    hearing_format: 'in_person',
    informal_review_available: true,
    informal_review_notes: 'Contact assessor first at (651) 266-2131 — many issues resolved by phone.',
    filing_fee_cents: 0,
    virtual_hearing_available: false,
    virtual_hearing_platform: null,
    pro_se_tips: 'Contact assessor first — many issues resolved by phone. Submit recent appraisal, sale records. Tax Court fees: $310 regular or $150 small claims.',
    notes: 'St. Paul. 90 Plato Blvd W. Phone resolution common.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },
  {
    county_fips: '27037',
    appeal_board_name: 'Dakota County Board of Appeal and Equalization',
    appeal_board_phone: '(651) 438-4200',
    portal_url: 'https://services.co.dakota.mn.us/Assessing/Forms/Assessor/Appeal.html',
    appeal_deadline_rule: 'Informal: March 11-May 1. Formal: early June meeting. Tax Court: April 30.',
    accepts_online_filing: false,
    hearing_format: 'in_person',
    informal_review_available: true,
    informal_review_notes: 'Informal review available March 11-May 1. Staff reviews and discusses valuation. Two-step process with formal meeting in early June.',
    filing_fee_cents: 0,
    virtual_hearing_available: false,
    virtual_hearing_platform: null,
    pro_se_tips: 'Two local appeal options: informal (March-May) and formal (June meeting). Have photos supporting appeal. Negotiation is the best approach. Tax Court: $310 regular or $150 small claims.',
    notes: 'Minneapolis south. Western Service Center, 14955 Galaxie Ave, Apple Valley.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },

  // ═══════════════════════════════════════════════════════════════════════
  // WASHINGTON / OREGON / INDIANA
  // ═══════════════════════════════════════════════════════════════════════
  {
    county_fips: '53053',
    appeal_board_name: 'Pierce County Board of Equalization',
    appeal_board_phone: '(253) 798-7415',
    portal_url: 'https://www.piercecountywa.gov/679/Appeals',
    appeal_deadline_rule: 'July 1 or 60 days from notice mailing, whichever is later',
    accepts_online_filing: false,
    hearing_format: 'in_person',
    informal_review_available: false,
    informal_review_notes: null,
    filing_fee_cents: 0,
    virtual_hearing_available: false,
    virtual_hearing_platform: null,
    pro_se_tips: 'Must use county-approved petition form only. Assessor responds at least 21 days before hearing. Submit evidence 21 days before hearing. Burden of proof on taxpayer. Market value evidence only — no assessment comparisons.',
    notes: 'Tacoma. 2401 S 35th St Room 176. 21-day evidence deadline.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },
  {
    county_fips: '53061',
    appeal_board_name: 'Snohomish County Board of Equalization',
    appeal_board_phone: '(425) 388-3407',
    portal_url: 'https://snohomishcountywa.gov/134/Board-of-Equalization',
    appeal_deadline_rule: '60 days from notice or July 1, whichever is later',
    accepts_online_filing: true,
    hearing_format: 'both',
    informal_review_available: false,
    informal_review_notes: null,
    filing_fee_cents: 0,
    virtual_hearing_available: true,
    virtual_hearing_platform: 'Zoom or phone — all hearings remote',
    pro_se_tips: 'ALL hearings are remote (Zoom/phone). Electronic filing via webform. Cannot use property assessment comparisons or personal hardship arguments. Market value evidence only.',
    notes: 'Everett. All-remote hearings. Webform filing only (not email).',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },
  {
    county_fips: '41051',
    appeal_board_name: 'Multnomah County Board of Equalization',
    appeal_board_phone: '(503) 988-2273',
    portal_url: 'https://multco.us/info/property-values-appeal-process',
    appeal_deadline_rule: 'December 31 annually',
    accepts_online_filing: true,
    hearing_format: 'in_person',
    informal_review_available: false,
    informal_review_notes: 'Contact DART office first via live chat/phone/email to discuss value before filing.',
    filing_fee_cents: 3000,
    virtual_hearing_available: false,
    virtual_hearing_platform: null,
    pro_se_tips: '$30/account filing fee. Form OR-B-RPP. Postmark or deliver by Dec 31. Hearings 10 minutes each, 9am-2pm Mon-Thu, Feb 15-April 15. Can submit written evidence only (no appearance). Avoid neighbor tax comparisons.',
    notes: 'Portland. $30 fee. Dec 31 deadline. Multnomah Building, 501 SE Hawthorne Blvd.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },
  {
    county_fips: '18097',
    appeal_board_name: 'Marion County PTABOA (Property Tax Assessment Board of Appeals)',
    appeal_board_phone: '(317) 327-4907',
    portal_url: 'https://www.indy.gov/activity/assessment-appeals-process',
    appeal_deadline_rule: 'June 15 or 45 days from Form 11 notice, whichever is later',
    accepts_online_filing: false,
    hearing_format: 'in_person',
    informal_review_available: true,
    informal_review_notes: 'Assessor office contacts you to meet/call after filing. Informal meeting before formal PTABOA hearing if no agreement.',
    filing_fee_cents: 0,
    virtual_hearing_available: false,
    virtual_hearing_platform: null,
    pro_se_tips: 'Two appeal types: Objective (statistical errors) or Subjective (opinion of value). Assessor contacts you for meeting first. Hearing examiner if no agreement. PTABOA decision within 120 days. Can appeal to Indiana Board of Tax Review after.',
    notes: 'Indianapolis. 200 E Washington St Suite 1360. Two appeal types.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },

  // ═══════════════════════════════════════════════════════════════════════
  // FLORIDA (additional 9) — All VAB system, 25-day TRIM deadline
  // ═══════════════════════════════════════════════════════════════════════
  {
    county_fips: '12031',
    appeal_board_name: 'Duval County Value Adjustment Board (VAB)',
    appeal_board_phone: '(904) 255-5500',
    portal_url: 'https://www.jacksonville.gov/departments/property-appraiser',
    appeal_deadline_rule: '25 days from TRIM notice mailing (typically mid-August)',
    accepts_online_filing: true,
    hearing_format: 'in_person',
    informal_review_available: true,
    informal_review_notes: 'Contact Property Appraiser for informal review after TRIM notice. File VAB petition regardless — deadline is firm.',
    filing_fee_cents: 1500,
    virtual_hearing_available: false,
    virtual_hearing_platform: null,
    pro_se_tips: 'Jacksonville. $15 per parcel. Special Magistrates conduct hearings. File petition BEFORE negotiating informally — deadline does not pause.',
    notes: 'Jacksonville metro. Standard FL VAB process.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },
  {
    county_fips: '12095',
    appeal_board_name: 'Orange County Value Adjustment Board (VAB)',
    appeal_board_phone: '(407) 836-5044',
    portal_url: 'https://www.occompt.com/199/Value-Adjustment-Board',
    appeal_deadline_rule: '25 days from TRIM notice mailing',
    accepts_online_filing: true,
    hearing_format: 'both',
    informal_review_available: true,
    informal_review_notes: 'Contact Property Appraiser for informal conference after TRIM mailing.',
    filing_fee_cents: 1500,
    virtual_hearing_available: true,
    virtual_hearing_platform: 'Virtual hearings available — check with clerk',
    pro_se_tips: 'Orlando. One of the few FL counties confirming virtual hearing option. $15/parcel. Online filing available through Comptroller.',
    notes: 'Orlando metro. Virtual hearings confirmed.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },
  {
    county_fips: '12103',
    appeal_board_name: 'Pinellas County Value Adjustment Board (VAB)',
    appeal_board_phone: '(727) 464-3207',
    portal_url: 'https://www.pcpao.gov/learn-about/value-adjustment-board',
    appeal_deadline_rule: '25 days from TRIM notice mailing',
    accepts_online_filing: true,
    hearing_format: 'in_person',
    informal_review_available: true,
    informal_review_notes: 'Contact Property Appraiser for informal review.',
    filing_fee_cents: 1500,
    virtual_hearing_available: false,
    virtual_hearing_platform: null,
    pro_se_tips: 'St. Petersburg. $15/parcel. File petition before informal negotiation — deadline firm.',
    notes: 'St. Petersburg/Clearwater metro.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },
  {
    county_fips: '12105',
    appeal_board_name: 'Polk County Value Adjustment Board (VAB)',
    appeal_board_phone: '(863) 534-4000',
    portal_url: 'https://www.polkclerkfl.gov/196/Value-Adjustment-Board',
    appeal_deadline_rule: '25 days from TRIM notice mailing',
    accepts_online_filing: true,
    hearing_format: 'in_person',
    informal_review_available: true,
    informal_review_notes: 'Contact Property Appraiser for informal review.',
    filing_fee_cents: 1500,
    virtual_hearing_available: false,
    virtual_hearing_platform: null,
    pro_se_tips: 'Lakeland. $15/parcel. Standard FL VAB process. File first, negotiate second.',
    notes: 'Lakeland area.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },
  {
    county_fips: '12071',
    appeal_board_name: 'Lee County Value Adjustment Board (VAB)',
    appeal_board_phone: '(239) 533-2174',
    portal_url: 'https://www.leeclerk.org/departments/value-adjustment-board-vab',
    appeal_deadline_rule: '25 days from TRIM notice mailing',
    accepts_online_filing: true,
    hearing_format: 'in_person',
    informal_review_available: true,
    informal_review_notes: 'Contact Property Appraiser for informal review.',
    filing_fee_cents: 1500,
    virtual_hearing_available: false,
    virtual_hearing_platform: null,
    pro_se_tips: 'Fort Myers. $15/parcel. Standard FL VAB. Special Magistrates conduct hearings.',
    notes: 'Fort Myers/Cape Coral metro.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },
  {
    county_fips: '12115',
    appeal_board_name: 'Sarasota County Value Adjustment Board (VAB)',
    appeal_board_phone: '(941) 861-8200',
    portal_url: 'https://www.sarasotaclerk.com/records/board-records/value-adjustment-board',
    appeal_deadline_rule: '25 days from TRIM notice mailing',
    accepts_online_filing: true,
    hearing_format: 'in_person',
    informal_review_available: true,
    informal_review_notes: 'Contact Property Appraiser for informal review.',
    filing_fee_cents: 1500,
    virtual_hearing_available: false,
    virtual_hearing_platform: null,
    pro_se_tips: 'Sarasota. $15/parcel. File first, negotiate second. TRIM typically mails mid-August.',
    notes: 'Sarasota metro.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },
  {
    county_fips: '12127',
    appeal_board_name: 'Volusia County Value Adjustment Board (VAB)',
    appeal_board_phone: '(386) 736-5901',
    portal_url: 'https://www.volusia.org/government/county-council/advisory-boards/value-adjustment-board.stml',
    appeal_deadline_rule: '25 days from TRIM notice mailing',
    accepts_online_filing: true,
    hearing_format: 'in_person',
    informal_review_available: true,
    informal_review_notes: 'Contact Property Appraiser for informal review.',
    filing_fee_cents: 1500,
    virtual_hearing_available: false,
    virtual_hearing_platform: null,
    pro_se_tips: 'Daytona Beach. $15/parcel. Standard FL VAB.',
    notes: 'Daytona Beach metro.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },
  {
    county_fips: '12117',
    appeal_board_name: 'Seminole County Value Adjustment Board (VAB)',
    appeal_board_phone: '(407) 665-7816',
    portal_url: 'https://www.seminoleclerk.org/value-adjustment-board/',
    appeal_deadline_rule: '25 days from TRIM notice mailing',
    accepts_online_filing: true,
    hearing_format: 'in_person',
    informal_review_available: true,
    informal_review_notes: 'Contact Property Appraiser for informal review.',
    filing_fee_cents: 1500,
    virtual_hearing_available: false,
    virtual_hearing_platform: null,
    pro_se_tips: 'Orlando suburb. $15/parcel. Standard FL VAB process.',
    notes: 'Orlando suburb.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },
  {
    county_fips: '12101',
    appeal_board_name: 'Pasco County Value Adjustment Board (VAB)',
    appeal_board_phone: '(352) 521-4274',
    portal_url: 'https://www.pascoclerk.com/307/Value-Adjustment-Board',
    appeal_deadline_rule: '25 days from TRIM notice mailing',
    accepts_online_filing: true,
    hearing_format: 'in_person',
    informal_review_available: true,
    informal_review_notes: 'Contact Property Appraiser for informal review.',
    filing_fee_cents: 1500,
    virtual_hearing_available: false,
    virtual_hearing_platform: null,
    pro_se_tips: 'Tampa suburb. $15/parcel. Standard FL VAB. File first, negotiate second.',
    notes: 'Tampa north suburb.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },

  // ═══════════════════════════════════════════════════════════════════════
  // TENNESSEE
  // ═══════════════════════════════════════════════════════════════════════
  {
    county_fips: '47157',
    appeal_board_name: 'Shelby County Board of Equalization',
    appeal_board_phone: '(901) 222-7001',
    portal_url: 'https://www.shelbycountytn.gov/116/Board-of-Equalization',
    appeal_deadline_rule: 'June 30 annually. State Board appeal by August 1.',
    accepts_online_filing: false,
    hearing_format: 'both',
    informal_review_available: true,
    informal_review_notes: 'Informal review with assessor available as first step.',
    filing_fee_cents: 0,
    virtual_hearing_available: true,
    virtual_hearing_platform: 'Phone hearings available per TN state law',
    pro_se_tips: 'Memphis. June 30 deadline. Informal review first. Phone hearings allowed by state law. Appeal to State Board by August 1 if county denies.',
    notes: 'Memphis metro. Phone hearings per TN law.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },
  {
    county_fips: '47037',
    appeal_board_name: 'Davidson County Board of Equalization / Nashville Property Assessor',
    appeal_board_phone: '(615) 862-6080',
    portal_url: 'https://www.padctn.org/appeal/',
    appeal_deadline_rule: 'Varies by year — check Property Assessor website. State Board appeal by August 1.',
    accepts_online_filing: true,
    hearing_format: 'both',
    informal_review_available: true,
    informal_review_notes: 'Nashville Property Assessor offers informal conferences.',
    filing_fee_cents: 0,
    virtual_hearing_available: true,
    virtual_hearing_platform: 'Phone hearings available per TN state law',
    pro_se_tips: 'Nashville. Online filing available. Informal conference with assessor first. Phone hearings per state law. State Board appeal by August 1.',
    notes: 'Nashville metro. Online filing available.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },
  {
    county_fips: '47065',
    appeal_board_name: 'Hamilton County Board of Equalization',
    appeal_board_phone: '(423) 209-7300',
    portal_url: 'https://www.hamiltontn.gov/AssessorOfProperty.aspx',
    appeal_deadline_rule: 'June 1 through June 20 annually',
    accepts_online_filing: false,
    hearing_format: 'both',
    informal_review_available: true,
    informal_review_notes: 'Informal review with assessor available.',
    filing_fee_cents: 0,
    virtual_hearing_available: true,
    virtual_hearing_platform: 'Phone hearings per TN state law',
    pro_se_tips: 'Chattanooga. June 1-20 window only — narrow. Phone hearings available. Informal review recommended first.',
    notes: 'Chattanooga. Narrow 20-day window.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },

  // ═══════════════════════════════════════════════════════════════════════
  // MISSOURI / INDIANA / KENTUCKY / ALABAMA / SOUTH CAROLINA
  // ═══════════════════════════════════════════════════════════════════════
  {
    county_fips: '29189',
    appeal_board_name: 'St. Louis County Board of Equalization',
    appeal_board_phone: '(314) 615-5124',
    portal_url: 'https://stlouiscountymo.gov/st-louis-county-government/board-of-equalization/',
    appeal_deadline_rule: 'Second Monday in July (odd years — MO reassesses biennially)',
    accepts_online_filing: true,
    hearing_format: 'in_person',
    informal_review_available: true,
    informal_review_notes: 'Contact assessor for informal review before board hearing.',
    filing_fee_cents: 0,
    virtual_hearing_available: false,
    virtual_hearing_platform: null,
    pro_se_tips: 'St. Louis County. Biennial reassessment — odd years only. Second Monday in July deadline. Online filing available.',
    notes: 'Biennial (odd years). July deadline.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },
  {
    county_fips: '29095',
    appeal_board_name: 'Jackson County Board of Equalization',
    appeal_board_phone: '(816) 881-3232',
    portal_url: 'https://www.jacksongov.org/Government/Boards-Commissions/Board-of-Equalization/Board-of-Equalization-Appeals',
    appeal_deadline_rule: 'July 14 (can extend to July 31 depending on year)',
    accepts_online_filing: true,
    hearing_format: 'both',
    informal_review_available: true,
    informal_review_notes: 'Informal review with assessor available.',
    filing_fee_cents: 0,
    virtual_hearing_available: true,
    virtual_hearing_platform: 'Phone hearings confirmed',
    pro_se_tips: 'Kansas City. July 14-31 window. Online filing. Phone hearings available. Biennial reassessment in odd years.',
    notes: 'Kansas City metro. Phone hearings confirmed.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },
  {
    county_fips: '18089',
    appeal_board_name: 'Lake County PTABOA (Property Tax Assessment Board of Appeals)',
    appeal_board_phone: '(219) 755-3100',
    portal_url: 'https://www.in.gov/dlgf/appeals-property-tax/',
    appeal_deadline_rule: 'June 15 or 45 days from Form 11 notice, whichever is later',
    accepts_online_filing: true,
    hearing_format: 'in_person',
    informal_review_available: true,
    informal_review_notes: 'Assessor contacts you for informal meeting after filing.',
    filing_fee_cents: 0,
    virtual_hearing_available: false,
    virtual_hearing_platform: null,
    pro_se_tips: 'Gary/Hammond. Same IN process as Marion County — objective or subjective appeal types. Assessor contacts you for meeting first.',
    notes: 'Gary/Hammond metro. Standard IN PTABOA process.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },
  {
    county_fips: '21111',
    appeal_board_name: 'Jefferson County Local Board of Assessment Appeals (LBAA)',
    appeal_board_phone: '(502) 574-6380',
    portal_url: 'https://jeffersonpva.ky.gov/property-assessment/conference/online-conference-documentation-and-appeals/',
    appeal_deadline_rule: 'Within 30 days of receiving assessment notice (typically January)',
    accepts_online_filing: true,
    hearing_format: 'in_person',
    informal_review_available: true,
    informal_review_notes: 'Conference with PVA (Property Valuation Administrator) as first step.',
    filing_fee_cents: 0,
    virtual_hearing_available: false,
    virtual_hearing_platform: null,
    pro_se_tips: 'Louisville. Two-stage: PVA conference first, then LBAA if unsatisfied. Online documentation available. January deadline typically.',
    notes: 'Louisville. PVA conference → LBAA two-stage process.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },
  {
    county_fips: '01073',
    appeal_board_name: 'Jefferson County Board of Equalization',
    appeal_board_phone: '(205) 325-5505',
    portal_url: 'https://boe.jccal.org/',
    appeal_deadline_rule: 'Within 30 days of assessment notice',
    accepts_online_filing: false,
    hearing_format: 'in_person',
    informal_review_available: true,
    informal_review_notes: 'Contact assessor for informal review before formal hearing.',
    filing_fee_cents: 0,
    virtual_hearing_available: false,
    virtual_hearing_platform: null,
    pro_se_tips: 'Birmingham. 30-day window from notice. In-person filing. Informal review with assessor recommended.',
    notes: 'Birmingham metro.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },
  {
    county_fips: '45045',
    appeal_board_name: 'Greenville County Board of Assessment Appeals',
    appeal_board_phone: '(864) 467-7300',
    portal_url: 'https://www.greenvillecounty.org/realproperty/appealsprocess.aspx',
    appeal_deadline_rule: '90 days after assessor mails notice during reassessment year',
    accepts_online_filing: false,
    hearing_format: 'in_person',
    informal_review_available: true,
    informal_review_notes: 'Contact Real Property Services for informal discussion.',
    filing_fee_cents: 0,
    virtual_hearing_available: false,
    virtual_hearing_platform: null,
    pro_se_tips: 'Greenville SC. 90-day window (generous). SC reassesses every 5 years — know your reassessment year.',
    notes: 'SC reassesses every 5 years.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },
  {
    county_fips: '45019',
    appeal_board_name: 'Charleston County Board of Assessment Appeals',
    appeal_board_phone: '(843) 958-4100',
    portal_url: 'https://www.charlestoncounty.gov/departments/assessment-appeals/',
    appeal_deadline_rule: '90 days after reassessment notice. 30 days for non-reassessment years.',
    accepts_online_filing: false,
    hearing_format: 'in_person',
    informal_review_available: true,
    informal_review_notes: 'Contact assessor for informal review.',
    filing_fee_cents: 0,
    virtual_hearing_available: false,
    virtual_hearing_platform: null,
    pro_se_tips: 'Charleston SC. Two different deadlines: 90 days in reassessment year, 30 days otherwise. Know which year you are in.',
    notes: 'Two deadline types depending on reassessment year.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },
  {
    county_fips: '45079',
    appeal_board_name: 'Richland County Board of Assessment Appeals',
    appeal_board_phone: '(803) 576-2640',
    portal_url: 'https://www.richlandcountysc.gov/Property-Business/Property-Valuation/Assessment-Appeal',
    appeal_deadline_rule: '90 days after reassessment notice',
    accepts_online_filing: true,
    hearing_format: 'in_person',
    informal_review_available: true,
    informal_review_notes: 'Contact Property Valuation office for informal review.',
    filing_fee_cents: 0,
    virtual_hearing_available: false,
    virtual_hearing_platform: null,
    pro_se_tips: 'Columbia SC. Online filing available. 90-day window. SC reassesses every 5 years.',
    notes: 'Columbia metro. Online filing available.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },

  // ═══════════════════════════════════════════════════════════════════════
  // UTAH
  // ═══════════════════════════════════════════════════════════════════════
  { county_fips: '49035', appeal_board_name: 'Salt Lake County Board of Equalization', appeal_board_phone: '(385) 468-7200', portal_url: 'https://www.saltlakecounty.gov/property-tax/property-tax-appeals/', appeal_deadline_rule: 'August 1 through September 15. Late appeals accepted until March 31.', accepts_online_filing: true, hearing_format: 'both', informal_review_available: true, informal_review_notes: 'Assessor review available. Email propertytaxappeals@saltlakecounty.gov.', filing_fee_cents: 0, virtual_hearing_available: false, virtual_hearing_platform: null, pro_se_tips: 'Online portal available for filing with evidence attachment. Contact Assessor first for informal review. Late appeals accepted until March 31.', notes: 'Email submissions accepted. Late appeal window until March 31.', last_verified_date: '2026-03-27', verified_by: 'Resourceful Research' },
  { county_fips: '49049', appeal_board_name: 'Utah County Board of Equalization', appeal_board_phone: null, portal_url: 'https://auditor.utahcounty.gov/valuation-appeals', appeal_deadline_rule: 'September 15 (online/email by 11:59 PM). Late appeals until March 31.', accepts_online_filing: true, hearing_format: 'in_person', informal_review_available: true, informal_review_notes: 'Assessor discussion before BOE. 70% historical success rate at informal stage.', filing_fee_cents: 0, virtual_hearing_available: false, virtual_hearing_platform: null, pro_se_tips: 'Provo. 70% success rate at informal hearings — always try informal first. Have parcel numbers ready. Submit docs as PDF/JPG/PNG.', notes: 'Provo. 70% informal success rate. Late window until March 31.', last_verified_date: '2026-03-27', verified_by: 'Resourceful Research' },

  // ═══════════════════════════════════════════════════════════════════════
  // IDAHO
  // ═══════════════════════════════════════════════════════════════════════
  { county_fips: '16001', appeal_board_name: 'Ada County Board of Equalization (County Commissioners)', appeal_board_phone: '(208) 287-7000', portal_url: 'https://adacounty.id.gov/commissioners/property-assessment-appeals/', appeal_deadline_rule: '4th Monday of June at 5:00 PM', accepts_online_filing: false, hearing_format: 'in_person', informal_review_available: true, informal_review_notes: 'Contact Assessor at (208) 287-7200 for preliminary review before formal appeal.', filing_fee_cents: 0, virtual_hearing_available: false, virtual_hearing_platform: null, pro_se_tips: 'Boise. Burden of proof on taxpayer. Use comparable sales, professional appraisal, or realtor analysis. Submit by fax (208-287-7009), mail, or in-person. 200 W. Front St., 3rd Floor.', notes: 'Boise. County Commissioners serve as BOE.', last_verified_date: '2026-03-27', verified_by: 'Resourceful Research' },

  // ═══════════════════════════════════════════════════════════════════════
  // OREGON (additional)
  // ═══════════════════════════════════════════════════════════════════════
  { county_fips: '41039', appeal_board_name: 'Lane County Property Value Appeals Board (PVAB)', appeal_board_phone: '(541) 682-4275', portal_url: null, appeal_deadline_rule: 'December 31 (postmarked or delivered)', accepts_online_filing: false, hearing_format: 'in_person', informal_review_available: false, informal_review_notes: null, filing_fee_cents: 3500, virtual_hearing_available: false, virtual_hearing_platform: null, pro_se_tips: 'Eugene. $35/account ($350 max for multiple under same ownership). Submit evidence 48 hours before hearing. 3-member board. Appeal to Oregon Tax Court within 30 days of decision.', notes: 'Eugene. $35 fee. 48-hour evidence deadline.', last_verified_date: '2026-03-27', verified_by: 'Resourceful Research' },
  { county_fips: '41067', appeal_board_name: 'Washington County Property Value Appeals Board', appeal_board_phone: '(503) 846-3854', portal_url: 'https://www.washingtoncountyor.gov/at/appraisal/', appeal_deadline_rule: 'December 31', accepts_online_filing: false, hearing_format: 'in_person', informal_review_available: true, informal_review_notes: 'Contact Assessor at (503) 846-8826 for preliminary review.', filing_fee_cents: 0, virtual_hearing_available: false, virtual_hearing_platform: null, pro_se_tips: 'Portland suburb. Free filing. Contact Assessor for forms and procedures.', notes: 'Portland suburb. Free.', last_verified_date: '2026-03-27', verified_by: 'Resourceful Research' },
  { county_fips: '41005', appeal_board_name: 'Clackamas County Property Value Appeals Board (PVAB)', appeal_board_phone: '(503) 655-8662', portal_url: 'https://www.clackamas.us/pvab', appeal_deadline_rule: 'December 31', accepts_online_filing: false, hearing_format: 'both', informal_review_available: false, informal_review_notes: null, filing_fee_cents: 0, virtual_hearing_available: true, virtual_hearing_platform: 'Zoom Webinar (ID: 231 378 5694, phone: 408-638-0968)', pro_se_tips: 'Portland suburb. Submit 5 copies of evidence with petition. Board meets 4 days/week Feb-April 15. Zoom hearings available. Strongly recommended to appear.', notes: 'Portland suburb. Zoom hearings. 1710 Red Soils Ct Suite 100, Oregon City.', last_verified_date: '2026-03-27', verified_by: 'Resourceful Research' },

  // ═══════════════════════════════════════════════════════════════════════
  // WASHINGTON (additional)
  // ═══════════════════════════════════════════════════════════════════════
  { county_fips: '53063', appeal_board_name: 'Spokane County Board of Equalization', appeal_board_phone: '(509) 477-2250', portal_url: 'https://www.spokanecounty.gov/154/Board-of-Equalization', appeal_deadline_rule: 'July 1 or 30 days from Change of Value Notice, whichever is later', accepts_online_filing: false, hearing_format: 'in_person', informal_review_available: true, informal_review_notes: 'Contact appraiser of record first — 60-day communication period for parties.', filing_fee_cents: 0, virtual_hearing_available: false, virtual_hearing_platform: null, pro_se_tips: 'Must use proper petition form (letter not acceptable). Contact appraiser of record first. Appointment only, M-F 8:30am-4pm (closed 12:30-1:30pm). 721 N Jefferson St Suite 201.', notes: 'Proper petition form required. Appointment only.', last_verified_date: '2026-03-27', verified_by: 'Resourceful Research' },
  { county_fips: '53067', appeal_board_name: 'Thurston County Board of Equalization', appeal_board_phone: null, portal_url: 'https://www.thurstoncountywa.gov/departments/board-equalization/appeal-process', appeal_deadline_rule: '30 days from Value Notice from Assessor', accepts_online_filing: false, hearing_format: 'in_person', informal_review_available: true, informal_review_notes: 'Assessor review available. Burden of proof on petitioner.', filing_fee_cents: 0, virtual_hearing_available: false, virtual_hearing_platform: null, pro_se_tips: 'Olympia. Hand-written signature required on petition. Include copy of Value Notice front page. CAUTION: 12-18 month wait for hearing typical.', notes: 'Olympia. 12-18 month hearing wait. 3000 Pacific Ave SE Room 244.', last_verified_date: '2026-03-27', verified_by: 'Resourceful Research' },

  // ═══════════════════════════════════════════════════════════════════════
  // COLORADO (additional)
  // ═══════════════════════════════════════════════════════════════════════
  { county_fips: '08041', appeal_board_name: 'El Paso County Board of Equalization', appeal_board_phone: '(719) 520-6430', portal_url: 'https://appeals.spatialest.com/co-elpaso', appeal_deadline_rule: 'May 1 to June 9 (Assessor). CBOE deadline: September 15.', accepts_online_filing: true, hearing_format: 'in_person', informal_review_available: true, informal_review_notes: 'Informal conference with Assessor available — does not waive right to formal hearing.', filing_fee_cents: 0, virtual_hearing_available: false, virtual_hearing_platform: null, pro_se_tips: 'Colorado Springs. Online appeal system. Informal conference available. Email boeappeals@elpasoco.com. 1675 W. Garden of the Gods Road.', notes: 'Colorado Springs. Spatialest portal.', last_verified_date: '2026-03-27', verified_by: 'Resourceful Research' },
  { county_fips: '08059', appeal_board_name: 'Jefferson County Board of Equalization', appeal_board_phone: '(303) 271-8666', portal_url: 'https://www.jeffco.us/435/Appealing-Real-Property-Valuation', appeal_deadline_rule: 'May 1 to June 9 (Assessor). CBOE by September 15. BOE must conclude by November 1.', accepts_online_filing: false, hearing_format: 'in_person', informal_review_available: true, informal_review_notes: 'Assessor mails Notice of Determination by August 15.', filing_fee_cents: 0, virtual_hearing_available: false, virtual_hearing_platform: null, pro_se_tips: 'Denver suburb. Appeal early in May. Three-tier: Assessor → CBOE → BAA/District Court.', notes: 'Denver suburb. November 1 conclusion deadline.', last_verified_date: '2026-03-27', verified_by: 'Resourceful Research' },
  { county_fips: '08013', appeal_board_name: 'Boulder County Board of Equalization', appeal_board_phone: '(303) 441-3530', portal_url: 'https://bouldercounty.gov/property-and-land/assessor/appeals/', appeal_deadline_rule: 'May 1 to June 8 (11:59 PM for online/email). CBOE by September 15.', accepts_online_filing: true, hearing_format: 'both', informal_review_available: true, informal_review_notes: 'Assessor review first. Email assessor@bouldercounty.org. Dropbox locations in Boulder, Longmont, Lafayette.', filing_fee_cents: 0, virtual_hearing_available: false, virtual_hearing_platform: null, pro_se_tips: 'Multiple submission options: online, fax (303-441-4996), dropbox, in-person. State BAA fee: $33.75-$101.25.', notes: 'Multiple filing methods. Dropbox locations.', last_verified_date: '2026-03-27', verified_by: 'Resourceful Research' },
  { county_fips: '08069', appeal_board_name: 'Larimer County Board of Equalization', appeal_board_phone: '(970) 498-7050', portal_url: 'https://www.larimer.gov/bocc/property-valuation-appeals', appeal_deadline_rule: 'May 1 through June 9 (Assessor). CBOE September 15-October 3.', accepts_online_filing: false, hearing_format: 'in_person', informal_review_available: true, informal_review_notes: 'Assessor mails Notice of Determination by August 15.', filing_fee_cents: 0, virtual_hearing_available: false, virtual_hearing_platform: null, pro_se_tips: 'Fort Collins. 15-minute CBOE hearings. $150 arbitration petition fee (refundable). Email cboeadmin@larimer.gov. 200 W. Oak Street.', notes: 'Fort Collins. $150 arbitration fee (refundable).', last_verified_date: '2026-03-27', verified_by: 'Resourceful Research' },

  // ═══════════════════════════════════════════════════════════════════════
  // NEW MEXICO / HAWAII / ALASKA / DELAWARE / RHODE ISLAND / NH / MAINE
  // ═══════════════════════════════════════════════════════════════════════
  { county_fips: '35001', appeal_board_name: 'Bernalillo County Valuation Protest Board', appeal_board_phone: '(505) 222-3700', portal_url: 'https://www.bernco.gov/assessor/', appeal_deadline_rule: '30-45 days from notice (varies by property type)', accepts_online_filing: false, hearing_format: 'in_person', informal_review_available: true, informal_review_notes: 'Assessor review available. Submit comparable sales, photos, appraisals.', filing_fee_cents: 0, virtual_hearing_available: false, virtual_hearing_platform: null, pro_se_tips: 'Albuquerque. Burden of proof on appellant. Assessor valuation presumed correct. 501 Tijeras NW, 1st Floor. Appeal Board decision to NM Court of Appeals.', notes: 'Albuquerque. Assessor presumed correct.', last_verified_date: '2026-03-27', verified_by: 'Resourceful Research' },
  { county_fips: '15003', appeal_board_name: 'Honolulu Board of Review', appeal_board_phone: null, portal_url: 'https://realproperty.honolulu.gov/appeals/file-an-appeal/', appeal_deadline_rule: 'December 15 to January 15 (annual appeal period)', accepts_online_filing: true, hearing_format: 'in_person', informal_review_available: false, informal_review_notes: null, filing_fee_cents: 5000, virtual_hearing_available: false, virtual_hearing_platform: null, pro_se_tips: 'Honolulu. $50 deposit (refundable if appeal sustained). Must prove assessment exceeds market value by >10%. Taxes must be paid during appeal — refunded if won. NOT fax/email. Appeal to Tax Appeal Court within 30 days.', notes: '$50 refundable deposit. 10% threshold. Must pay taxes during appeal.', last_verified_date: '2026-03-27', verified_by: 'Resourceful Research' },
  { county_fips: '02020', appeal_board_name: 'Anchorage Board of Equalization', appeal_board_phone: '(907) 343-6500', portal_url: 'https://www.muni.org/Departments/finance/property_appraisal/Appeals/', appeal_deadline_rule: '30 days from Assessment Notice mailing (typically January)', accepts_online_filing: false, hearing_format: 'in_person', informal_review_available: true, informal_review_notes: 'Assessor meeting available as first step. Evidence must be filed within 45 days of assessment notice.', filing_fee_cents: 3000, virtual_hearing_available: false, virtual_hearing_platform: null, pro_se_tips: 'Anchorage. Filing fee by property value: $30 (under $500K), $100 ($500K-$2M), $200 ($2M+), $1000 ($2M+). Refundable if resolved before hearing. BOE meets Feb/March. Superior Court appeal within 30 days.', notes: 'Scaled filing fees. Jan notice → 30 days. BOE Feb/March.', last_verified_date: '2026-03-27', verified_by: 'Resourceful Research' },
  { county_fips: '10003', appeal_board_name: 'New Castle County Board of Assessment Review', appeal_board_phone: '(302) 395-5520', portal_url: 'https://www.newcastlede.gov/390/Board-of-Assessment-Review', appeal_deadline_rule: 'January 1 through March 14 annually', accepts_online_filing: false, hearing_format: 'in_person', informal_review_available: false, informal_review_notes: null, filing_fee_cents: 0, virtual_hearing_available: false, virtual_hearing_platform: null, pro_se_tips: 'Wilmington. 15 minutes to present. Only evidence submitted with original appeal can be discussed at hearing — submit everything upfront. Up to 6 comparable sales, photos, repair estimates, appraisal.', notes: 'Wilmington. 87 Reads Way. M-F 8am-4pm. Evidence locked at filing.', last_verified_date: '2026-03-27', verified_by: 'Resourceful Research' },
  { county_fips: '44007', appeal_board_name: 'Providence Board of Tax Assessment Review (BTAR)', appeal_board_phone: null, portal_url: 'https://www.providenceri.gov/tax-assessor/property-tax-appeals/', appeal_deadline_rule: '90 days from first tax payment due date (to Assessor). 30 days from Assessor decision to BTAR.', accepts_online_filing: false, hearing_format: 'in_person', informal_review_available: true, informal_review_notes: 'Assessor review first — Assessor has 45 days to respond. BTAR must decide within 90 days of filing.', filing_fee_cents: 0, virtual_hearing_available: false, virtual_hearing_platform: null, pro_se_tips: 'Providence RI. Two-stage: Assessor (45-day response) → BTAR (90-day decision). Grounds: overvaluation, disproportionate assessment, misclassification, illegality. Appeal to Superior Court within 30 days of BTAR.', notes: 'Two-stage with strict timelines. Different processes for residential vs commercial.', last_verified_date: '2026-03-27', verified_by: 'Resourceful Research' },
  { county_fips: '33011', appeal_board_name: 'Board of Assessors (municipal) / NH Board of Tax and Land Appeals (BTLA)', appeal_board_phone: '(603) 271-2578', portal_url: null, appeal_deadline_rule: 'March 1 to local Board of Assessors. If no action by July 1, appeal to BTLA or Superior Court.', accepts_online_filing: false, hearing_format: 'in_person', informal_review_available: true, informal_review_notes: 'Informal review with local Assessor available.', filing_fee_cents: 0, virtual_hearing_available: false, virtual_hearing_platform: null, pro_se_tips: 'Manchester/Nashua. 20 separate municipal assessors — contact YOUR town. March 1 local deadline. If Board of Assessors silent by July 1, appeal to BTLA or Hillsborough County Superior Court (choose one, not both).', notes: '20 municipal assessors. March 1 local, July 1 escalation trigger.', last_verified_date: '2026-03-27', verified_by: 'Resourceful Research' },
  { county_fips: '23005', appeal_board_name: 'Cumberland County Board of Assessment Review (BAR)', appeal_board_phone: '(207) 699-2475', portal_url: 'https://www.cumberlandcountyme.gov/departments/regional_assessing/', appeal_deadline_rule: '185 days after municipality commitment date (Abatement). 60 days after Assessor decision to BAR.', accepts_online_filing: false, hearing_format: 'in_person', informal_review_available: true, informal_review_notes: 'Assessor abatement review first — Assessor has 60 days to respond. May request more info (706A Request).', filing_fee_cents: 10000, virtual_hearing_available: false, virtual_hearing_platform: null, pro_se_tips: 'Portland ME. $100 appeals conference fee (refundable/waivable for hardship). Regional assessing provides centralized services. Submit supporting info 14 days before BAR hearing.', notes: 'Portland ME. $100 fee (waivable). 14-day evidence deadline. Regional assessing office.', last_verified_date: '2026-03-27', verified_by: 'Resourceful Research' },
];

async function seedExtendedCounties() {
  const supabaseUrl = process.env.SUPABASE_URL;
  const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

  if (!supabaseUrl || !supabaseKey) {
    console.error('Error: SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY are required');
    process.exit(1);
  }

  const { createClient } = await import('@supabase/supabase-js');
  const supabase = createClient(supabaseUrl, supabaseKey);

  console.log(`Seeding intelligence for ${EXTENDED_COUNTIES.length} extended counties...`);

  let updated = 0;
  let errors = 0;

  for (const county of EXTENDED_COUNTIES) {
    const { county_fips, ...updateData } = county;

    const { error } = await supabase
      .from('county_rules')
      .update(updateData as never)
      .eq('county_fips', county_fips);

    if (error) {
      console.error(`  FAILED ${county_fips}: ${error.message}`);
      errors++;
    } else {
      updated++;
      console.log(`  Updated ${county_fips}`);
    }
  }

  console.log(`\nDone! Updated ${updated} counties. Errors: ${errors}`);
  console.log('Run seed-top-counties.ts first if you haven\'t already.');
}

seedExtendedCounties().catch((err) => {
  console.error('Fatal error:', err);
  process.exit(1);
});
