// ─── Top County Intelligence Seed Data ────────────────────────────────────────
// Real appeal strategies, deadlines, portal URLs, and filing intelligence
// for the top 25 US counties by property tax appeal volume.
// Run after seed-counties.ts to upgrade these counties with elite-level data.
//
// Usage:
//   SUPABASE_URL=... SUPABASE_SERVICE_ROLE_KEY=... npx tsx scripts/seed-top-counties.ts

interface CountyIntelligence {
  county_fips: string;
  appeal_board_name: string;
  appeal_board_phone: string | null;
  portal_url: string | null;
  appeal_deadline_rule: string;
  next_appeal_deadline: string | null;
  assessment_cycle: string;
  current_tax_year: number;
  accepts_online_filing: boolean;
  accepts_email_filing: boolean;
  requires_mail_filing: boolean;
  hearing_typically_required: boolean;
  hearing_format: string | null;
  hearing_duration_minutes: number | null;
  virtual_hearing_available: boolean;
  virtual_hearing_platform: string | null;
  informal_review_available: boolean;
  informal_review_notes: string | null;
  filing_fee_cents: number;
  appeal_form_name: string | null;
  form_download_url: string | null;
  evidence_requirements: string[];
  required_documents: string[];
  authorized_rep_allowed: boolean;
  further_appeal_body: string | null;
  further_appeal_deadline_rule: string | null;
  state_appeal_board_name: string | null;
  state_appeal_board_url: string | null;
  pro_se_tips: string | null;
  notes: string | null;
  last_verified_date: string;
  verified_by: string;
}

const TOP_COUNTIES: CountyIntelligence[] = [
  // ── COOK COUNTY, IL (17031) ─────────────────────────────────────────────
  {
    county_fips: '17031',
    appeal_board_name: 'Cook County Board of Review',
    appeal_board_phone: '(312) 443-7550',
    portal_url: 'https://appeals.cookcountyboardofreview.com/',
    appeal_deadline_rule: 'Varies by township — 30 days from publication of assessment list. 38 townships file on staggered monthly schedule (Jan–Oct).',
    next_appeal_deadline: null,
    assessment_cycle: 'Triennial',
    current_tax_year: 2025,
    accepts_online_filing: true,
    accepts_email_filing: false,
    requires_mail_filing: false,
    hearing_typically_required: false,
    hearing_format: 'written_only',
    hearing_duration_minutes: null,
    virtual_hearing_available: false,
    virtual_hearing_platform: null,
    informal_review_available: true,
    informal_review_notes: 'Cook County Assessor offers initial informal review before Board of Review. Call (312) 443-7550 for Taxpayer Assistance. Also file with Assessor first at cookcountyassessoril.gov/online-appeals before escalating to Board of Review.',
    filing_fee_cents: 0,
    appeal_form_name: 'Board of Review Complaint Form',
    form_download_url: 'https://appeals.cookcountyboardofreview.com/',
    evidence_requirements: ['Comparable sales (minimum 3, within last 3 years)', 'Professional appraisal (USPAP compliant)', 'Property photographs', 'Condition documentation'],
    required_documents: ['Appeal form', 'Comparable sales evidence', 'Photos of property condition', 'Tax bill (if available)'],
    authorized_rep_allowed: true,
    further_appeal_body: 'Illinois Property Tax Appeal Board (PTAB)',
    further_appeal_deadline_rule: '30 days from Board of Review decision postmark',
    state_appeal_board_name: 'Illinois Property Tax Appeal Board (PTAB)',
    state_appeal_board_url: 'https://www.ptab.illinois.gov/efile/',
    pro_se_tips: 'Cook County Board of Review win rate is ~62%. Lead with comparable sales — the board weighs market data heavily. Township-specific deadlines are critical — check your exact township opening date. File with the Assessor FIRST (free, online), then escalate to Board of Review if denied. Commercial properties appeal 64% of the time vs 27% residential.',
    notes: '38 townships with staggered filing windows. Collective savings: $3.3B businesses, $2.8B homeowners.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },

  // ── HARRIS COUNTY, TX (48201) ───────────────────────────────────────────
  {
    county_fips: '48201',
    appeal_board_name: 'Harris Central Appraisal District (HCAD) — Appraisal Review Board',
    appeal_board_phone: '(713) 957-7800',
    portal_url: 'https://hcad.org/hcad-online-services/ifile-protest/',
    appeal_deadline_rule: 'May 15 or 30 days after Notice of Appraised Value is mailed, whichever is later',
    next_appeal_deadline: '2026-05-15',
    assessment_cycle: 'Annual',
    current_tax_year: 2026,
    accepts_online_filing: true,
    accepts_email_filing: false,
    requires_mail_filing: false,
    hearing_typically_required: true,
    hearing_format: 'both',
    hearing_duration_minutes: 15,
    virtual_hearing_available: true,
    virtual_hearing_platform: 'Phone or videoconference — must request 10 days before hearing',
    informal_review_available: true,
    informal_review_notes: 'iSettle settlement system available online. 89.2% of informal protests succeed — always try informal first. 39% of value reductions occur at informal stage. Contact HCAD for informal conference appointment.',
    filing_fee_cents: 0,
    appeal_form_name: 'iFile Protest (online)',
    form_download_url: 'https://hcad.org/hcad-online-services/ifile-protest/',
    evidence_requirements: ['Comparable property sales', 'Assessment-to-sale ratios', 'Professional appraisal', 'Property condition photos', 'Market analysis'],
    required_documents: ['Notice of Appraised Value (for iFile number)', 'Comparable sales evidence', 'Photos', 'Appraisal (if available)'],
    authorized_rep_allowed: true,
    further_appeal_body: 'District Court or Binding Arbitration',
    further_appeal_deadline_rule: '60 days from ARB order date',
    state_appeal_board_name: null,
    state_appeal_board_url: null,
    pro_se_tips: 'Harris County has the highest informal protest success rate in Texas at 89.2%. ALWAYS file informal protest first via iSettle. You need your iFile number from the Notice of Appraised Value to file online. File early — the system gets heavy traffic near May 15. Request phone/video hearing if you cannot attend in person (must request 10 days ahead).',
    notes: '217,394 of 241,930 accounts resolved informally with reductions. Residential 85-95% success, commercial 70-75%.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },

  // ── MARICOPA COUNTY, AZ (04013) ────────────────────────────────────────
  {
    county_fips: '04013',
    appeal_board_name: 'Maricopa County Assessor — Appeals Division',
    appeal_board_phone: '(602) 506-3406',
    portal_url: 'https://www.mcassessor.maricopa.gov/page/appeals/',
    appeal_deadline_rule: '60 days from Notice of Valuation mailing date',
    next_appeal_deadline: '2026-04-21',
    assessment_cycle: 'Annual',
    current_tax_year: 2027,
    accepts_online_filing: true,
    accepts_email_filing: false,
    requires_mail_filing: false,
    hearing_typically_required: true,
    hearing_format: 'in_person',
    hearing_duration_minutes: 15,
    virtual_hearing_available: false,
    virtual_hearing_platform: null,
    informal_review_available: true,
    informal_review_notes: 'Meet with Assessor office or supply evidence informally before formal appeal. Call (602) 506-3406 to schedule. Documentation is REQUIRED at Assessor level or appeal will be denied.',
    filing_fee_cents: 0,
    appeal_form_name: 'Appeal Application',
    form_download_url: 'https://www.mcassessor.maricopa.gov/file/appeals/forms/Appeal-Process-Informational-Handout.pdf',
    evidence_requirements: ['Recent appraisal (REQUIRED)', 'Comparable sales', 'Legal classification proof', 'Property condition evidence'],
    required_documents: ['Appeal form', 'Appraisal or comparable sales', 'Photos', 'Property condition documentation'],
    authorized_rep_allowed: true,
    further_appeal_body: 'Arizona State Board of Equalization (SBOE)',
    further_appeal_deadline_rule: '25 days from Assessor decision',
    state_appeal_board_name: 'Arizona State Board of Equalization',
    state_appeal_board_url: 'https://sboe.az.gov/taxpayers/how-file-appeal',
    pro_se_tips: 'Documentation is REQUIRED at the Assessor level — bring evidence or your appeal will be denied outright. Multi-level system: Assessor → SBOE → Tax Court. Start with the Assessor for the fastest resolution.',
    notes: 'Three-level appeal system. Phone contact preferred for scheduling.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },

  // ── LOS ANGELES COUNTY, CA (06037) ─────────────────────────────────────
  {
    county_fips: '06037',
    appeal_board_name: 'Los Angeles County Assessment Appeals Board (AAB)',
    appeal_board_phone: '(213) 974-1471',
    portal_url: 'https://aab.lacounty.gov/',
    appeal_deadline_rule: 'July 2 through November 30 (annual window). Supplemental assessments: 60 days from mailing.',
    next_appeal_deadline: '2026-11-30',
    assessment_cycle: 'Annual (Prop 13 base year)',
    current_tax_year: 2026,
    accepts_online_filing: true,
    accepts_email_filing: false,
    requires_mail_filing: false,
    hearing_typically_required: true,
    hearing_format: 'both',
    hearing_duration_minutes: 20,
    virtual_hearing_available: true,
    virtual_hearing_platform: 'Hybrid — in-person and virtual options available',
    informal_review_available: true,
    informal_review_notes: 'Contact Public Interaction Unit at (213) 974-1471 for assessment review before formal filing.',
    filing_fee_cents: 4600,
    appeal_form_name: 'Assessment Appeals Application (Form AAB 103)',
    form_download_url: 'https://lacaab.lacounty.gov/helpfiles/forms/aab103.pdf',
    evidence_requirements: ['Comparable property sales', 'Professional appraisal', 'Property condition documentation', 'Market analysis'],
    required_documents: ['Form AAB 103', 'Comparable sales', 'Photos', 'Appraisal (recommended)'],
    authorized_rep_allowed: true,
    further_appeal_body: 'Superior Court',
    further_appeal_deadline_rule: '6 months from AAB decision',
    state_appeal_board_name: null,
    state_appeal_board_url: null,
    pro_se_tips: 'LA County has a $46 filing fee (fee waivers available for hardship). The July 2–Nov 30 window is generous — use it. Supplemental assessments from recent purchases have a separate 60-day deadline. Online filing at aab.lacounty.gov is fastest.',
    notes: 'Prop 13 limits annual increases to 2%. Appeals focus on base year value or decline in value.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },

  // ── DALLAS COUNTY, TX (48113) ───────────────────────────────────────────
  {
    county_fips: '48113',
    appeal_board_name: 'Dallas Central Appraisal District (DCAD) — Appraisal Review Board',
    appeal_board_phone: '(214) 631-0910',
    portal_url: 'https://www.dallascad.org/',
    appeal_deadline_rule: 'May 15 or 30 days after Notice mailed, whichever is later',
    next_appeal_deadline: '2026-05-15',
    assessment_cycle: 'Annual',
    current_tax_year: 2026,
    accepts_online_filing: true,
    accepts_email_filing: false,
    requires_mail_filing: false,
    hearing_typically_required: true,
    hearing_format: 'both',
    hearing_duration_minutes: 15,
    virtual_hearing_available: true,
    virtual_hearing_platform: 'Phone or video — request when filing protest',
    informal_review_available: true,
    informal_review_notes: 'Informal conference available through ARB process. Texas districts average 80-90% informal settlement success.',
    filing_fee_cents: 0,
    appeal_form_name: 'uFile Protest (online)',
    form_download_url: 'https://dallascad.org/Forms/Protest_Process.pdf',
    evidence_requirements: ['Comparable property sales', 'Appraisal documentation', 'Property condition evidence', 'Market analysis'],
    required_documents: ['Notice of Appraised Value (for PIN)', 'Comparable sales', 'Photos', 'Appraisal (if available)'],
    authorized_rep_allowed: true,
    further_appeal_body: 'District Court or Binding Arbitration',
    further_appeal_deadline_rule: '60 days from ARB order',
    state_appeal_board_name: null,
    state_appeal_board_url: null,
    pro_se_tips: 'PIN from your Notice of Appraised Value is required for online filing. System gets heavy traffic near May 15 — file early. Technical difficulties do NOT extend the deadline.',
    notes: null,
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },

  // ── CUYAHOGA COUNTY, OH (39035) ────────────────────────────────────────
  {
    county_fips: '39035',
    appeal_board_name: 'Cuyahoga County Board of Revision',
    appeal_board_phone: '(216) 443-7195',
    portal_url: 'https://cuyahogabor.org/',
    appeal_deadline_rule: 'January 1 through March 31 — NO EXTENSIONS (Ohio Revised Code 5715.19)',
    next_appeal_deadline: '2027-03-31',
    assessment_cycle: 'Sexennial (6-year reappraisal) with triennial updates',
    current_tax_year: 2025,
    accepts_online_filing: true,
    accepts_email_filing: false,
    requires_mail_filing: false,
    hearing_typically_required: true,
    hearing_format: 'in_person',
    hearing_duration_minutes: 15,
    virtual_hearing_available: false,
    virtual_hearing_platform: null,
    informal_review_available: true,
    informal_review_notes: 'Informal conference encouraged before filing. Contact Board of Revision at (216) 443-7195.',
    filing_fee_cents: 0,
    appeal_form_name: 'E-Complaint Form',
    form_download_url: 'https://app.cuyahogacounty.us/borcomplaints/',
    evidence_requirements: ['Comparable property sales', 'Professional appraisal', 'Property photographs', 'Income/expense documentation (commercial)'],
    required_documents: ['Complaint form', 'Comparable sales', 'Appraisal', 'Photos'],
    authorized_rep_allowed: true,
    further_appeal_body: 'Ohio Board of Tax Appeals',
    further_appeal_deadline_rule: '30 days from Board of Revision decision',
    state_appeal_board_name: 'Ohio Board of Tax Appeals',
    state_appeal_board_url: null,
    pro_se_tips: 'STRICT no-extension policy — March 31 is absolute. E-filing takes ~10 minutes and gives instant PDF confirmation. No notary required for e-filing. IMPORTANT: Private courier postmarks (FedEx, UPS) do NOT count — only USPS postmark matters if mailing.',
    notes: 'E-filing strongly preferred. 40% of filers receive value adjustments.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },

  // ── MIAMI-DADE COUNTY, FL (12086) ──────────────────────────────────────
  {
    county_fips: '12086',
    appeal_board_name: 'Miami-Dade Value Adjustment Board (VAB)',
    appeal_board_phone: '(305) 375-2861',
    portal_url: 'https://www.miamidadeclerk.com/clerk/value-adjustment-board.page',
    appeal_deadline_rule: '25 days from TRIM notice mailing date (typically mid-August). VAB CANNOT extend this deadline.',
    next_appeal_deadline: null,
    assessment_cycle: 'Annual',
    current_tax_year: 2026,
    accepts_online_filing: true,
    accepts_email_filing: false,
    requires_mail_filing: false,
    hearing_typically_required: true,
    hearing_format: 'in_person',
    hearing_duration_minutes: 15,
    virtual_hearing_available: false,
    virtual_hearing_platform: null,
    informal_review_available: true,
    informal_review_notes: 'Property Appraiser offers informal "interview period" after TRIM mailing. Call (305) 375-2861 to request review. Negotiate informally BUT file your VAB petition anyway — the deadline is firm even during negotiations.',
    filing_fee_cents: 1500,
    appeal_form_name: 'VAB Petition Form',
    form_download_url: 'https://www.miamidadepa.gov/pa/property-assessments/appeal.page',
    evidence_requirements: ['Comparable property sales', 'Professional appraisal', 'Property condition documentation', 'Market analysis'],
    required_documents: ['VAB Petition Form', 'Comparable sales', 'Photos', 'Appraisal (recommended)'],
    authorized_rep_allowed: true,
    further_appeal_body: 'Circuit Court',
    further_appeal_deadline_rule: '60 days from VAB decision',
    state_appeal_board_name: null,
    state_appeal_board_url: null,
    pro_se_tips: 'TRIM notices typically mail mid-August. You have exactly 25 days — no extensions. Special Magistrates (licensed appraisers or attorneys) conduct hearings. File your petition BEFORE negotiating informally — the deadline is firm regardless of ongoing discussions.',
    notes: '$15/parcel filing fee. Late filing only with proven extenuating circumstances (medical emergency, natural disaster).',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },

  // ── TRAVIS COUNTY, TX (48453) ──────────────────────────────────────────
  {
    county_fips: '48453',
    appeal_board_name: 'Travis Central Appraisal District (TCAD) — Appraisal Review Board',
    appeal_board_phone: '(512) 834-9317',
    portal_url: 'https://traviscad.org/efile/',
    appeal_deadline_rule: 'May 15 or 30 days after Notice mailed, whichever is later',
    next_appeal_deadline: '2026-05-15',
    assessment_cycle: 'Annual',
    current_tax_year: 2026,
    accepts_online_filing: true,
    accepts_email_filing: false,
    requires_mail_filing: false,
    hearing_typically_required: true,
    hearing_format: 'both',
    hearing_duration_minutes: 15,
    virtual_hearing_available: true,
    virtual_hearing_platform: 'Phone or video — must request 10 days before hearing',
    informal_review_available: true,
    informal_review_notes: 'Settlement negotiations available through online portal. Upload evidence, review appraiser evidence, and see settlement offers online. Texas averages 80-90% informal settlement success.',
    filing_fee_cents: 0,
    appeal_form_name: 'Online Protest (e-File)',
    form_download_url: 'https://traviscad.org/efile/',
    evidence_requirements: ['Comparable property sales', 'Professional appraisal', 'Property condition documentation', 'Assessment-to-value ratio analysis'],
    required_documents: ['Protest form', 'Comparable sales', 'Photos', 'Market analysis'],
    authorized_rep_allowed: true,
    further_appeal_body: 'District Court or Binding Arbitration',
    further_appeal_deadline_rule: '60 days from ARB order',
    state_appeal_board_name: null,
    state_appeal_board_url: null,
    pro_se_tips: 'File early — heavy traffic near May 15. TCAD must RECEIVE by deadline (postmark does not count for mail). Online filing gives instant confirmation. You can upload evidence and see settlement offers through the online portal. Request phone/video hearing 10 days in advance if needed.',
    notes: 'TCAD office: 850 East Anderson Lane, Austin TX 78752. Mail: PO Box 149012, Austin TX 78714.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },

  // ── TARRANT COUNTY, TX (48439) ─────────────────────────────────────────
  {
    county_fips: '48439',
    appeal_board_name: 'Tarrant Appraisal District (TAD) — Appraisal Review Board',
    appeal_board_phone: '(817) 284-0024',
    portal_url: 'https://www.tad.org/',
    appeal_deadline_rule: 'May 15 or 30 days after Notice mailed, whichever is later',
    next_appeal_deadline: '2026-05-15',
    assessment_cycle: 'Annual',
    current_tax_year: 2026,
    accepts_online_filing: true,
    accepts_email_filing: false,
    requires_mail_filing: false,
    hearing_typically_required: true,
    hearing_format: 'both',
    hearing_duration_minutes: 15,
    virtual_hearing_available: true,
    virtual_hearing_platform: 'Phone or video — standard accommodation',
    informal_review_available: true,
    informal_review_notes: 'Online value negotiation system available through TAD portal. Texas averages 80-90% informal settlement.',
    filing_fee_cents: 0,
    appeal_form_name: 'Online Protest',
    form_download_url: 'https://www.tad.org/',
    evidence_requirements: ['Comparable property sales', 'Professional appraisal', 'Market analysis', 'Property condition evidence'],
    required_documents: ['Protest form', 'Comparable sales', 'Photos', 'Assessment comparisons'],
    authorized_rep_allowed: true,
    further_appeal_body: 'District Court or Binding Arbitration',
    further_appeal_deadline_rule: '60 days from ARB order',
    state_appeal_board_name: null,
    state_appeal_board_url: null,
    pro_se_tips: 'TAD offers online value negotiation — try it before formal hearing. Check TAD website for current filing status and deadlines.',
    notes: null,
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },

  // ── BEXAR COUNTY, TX (48029) ───────────────────────────────────────────
  {
    county_fips: '48029',
    appeal_board_name: 'Bexar Central Appraisal District (BCAD) — Appraisal Review Board',
    appeal_board_phone: '(210) 242-2432',
    portal_url: 'https://bcad.org/online-portal/',
    appeal_deadline_rule: 'May 15 or 30 days after Notice mailed, whichever is later',
    next_appeal_deadline: '2026-05-15',
    assessment_cycle: 'Annual',
    current_tax_year: 2026,
    accepts_online_filing: true,
    accepts_email_filing: false,
    requires_mail_filing: false,
    hearing_typically_required: true,
    hearing_format: 'both',
    hearing_duration_minutes: 15,
    virtual_hearing_available: true,
    virtual_hearing_platform: 'Phone or video — by request',
    informal_review_available: true,
    informal_review_notes: 'ARB process includes informal negotiations. Texas averages 80-90% informal settlement success.',
    filing_fee_cents: 0,
    appeal_form_name: 'Form 50-132 (Notice of Protest)',
    form_download_url: 'https://bcad.org/wp-content/uploads/2024/03/2024-PROTEST-FORM-as-of-03-18-24.pdf',
    evidence_requirements: ['Comparable property sales', 'Professional appraisal', 'Property condition documentation', 'Market analysis'],
    required_documents: ['Form 50-132 or online protest', 'Comparable sales', 'Photos', 'Appraisal (if available)'],
    authorized_rep_allowed: true,
    further_appeal_body: 'District Court or Binding Arbitration',
    further_appeal_deadline_rule: '60 days from ARB order',
    state_appeal_board_name: null,
    state_appeal_board_url: null,
    pro_se_tips: 'Owner/Agent ID and PIN required for online portal. E-filing is fastest. Alternative: Mail to PO Box 830248, San Antonio TX 78283. Fax: 210-242-2454. In-person: 411 N Frio St, San Antonio TX 78207.',
    notes: 'Help center: https://help.bcad.org',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },

  // ── FULTON COUNTY, GA (13121) ──────────────────────────────────────────
  {
    county_fips: '13121',
    appeal_board_name: 'Fulton County Board of Assessors',
    appeal_board_phone: '(404) 612-6440',
    portal_url: 'https://fultonassessor.org/property-appeals/',
    appeal_deadline_rule: 'Within 45 days of Notice of Assessment date',
    next_appeal_deadline: null,
    assessment_cycle: 'Annual',
    current_tax_year: 2026,
    accepts_online_filing: true,
    accepts_email_filing: false,
    requires_mail_filing: false,
    hearing_typically_required: true,
    hearing_format: 'both',
    hearing_duration_minutes: 15,
    virtual_hearing_available: true,
    virtual_hearing_platform: 'Virtual hearings available. Evidence must be submitted to boeevidence@fultoncountyga.gov at least 48 hours before hearing.',
    informal_review_available: true,
    informal_review_notes: 'Contact Board of Assessors at (404) 612-6440 for informal review/discussion before formal appeal.',
    filing_fee_cents: 0,
    appeal_form_name: 'Board of Assessors Appeal Form',
    form_download_url: 'https://fultonassessor.org/property-appeals/',
    evidence_requirements: ['Comparable property sales', 'Professional appraisal', 'Property condition documentation', 'Market analysis'],
    required_documents: ['Appeal form', 'Comparable sales', 'Photos', 'Appraisal (recommended)'],
    authorized_rep_allowed: true,
    further_appeal_body: 'Board of Equalization → Superior Court',
    further_appeal_deadline_rule: '30 days from Board of Assessors decision',
    state_appeal_board_name: null,
    state_appeal_board_url: null,
    pro_se_tips: 'Fulton has a generous 45-day window (longer than most). Online filing is preferred. IMPORTANT: Evidence submitted less than 48 hours before virtual hearing will NOT be admitted. No email/fax filing — use online portal or in-person. Five office locations throughout county.',
    notes: 'Appeals NOT accepted via email or fax — online or in-person only.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },

  // ── KING COUNTY, WA (53033) ────────────────────────────────────────────
  {
    county_fips: '53033',
    appeal_board_name: 'King County Board of Appeals and Equalization (BAE)',
    appeal_board_phone: '(206) 296-0538',
    portal_url: 'https://kingcounty.gov/en/dept/assessor/buildings-and-property/property-value-and-information/appealing-a-valuation',
    appeal_deadline_rule: 'July 1 of assessment year OR 60 days from value notice mailing, whichever is LATER',
    next_appeal_deadline: null,
    assessment_cycle: 'Annual',
    current_tax_year: 2026,
    accepts_online_filing: true,
    accepts_email_filing: false,
    requires_mail_filing: false,
    hearing_typically_required: true,
    hearing_format: 'in_person',
    hearing_duration_minutes: 20,
    virtual_hearing_available: false,
    virtual_hearing_platform: null,
    informal_review_available: true,
    informal_review_notes: 'Contact county assessor before filing for informal review. Email: boe@kingcounty.gov.',
    filing_fee_cents: 0,
    appeal_form_name: 'eAppeals Form',
    form_download_url: 'https://kingcounty.gov/en/independents/governance-and-leadership/government-oversight/board-appeals-equalization/appeals-forms',
    evidence_requirements: ['Comparable sales (recent)', 'Professional appraisal', 'Repair cost estimates', 'Property condition documentation'],
    required_documents: ['Appeal form', 'Evidence package (21 business days before hearing)', 'Comparable sales', 'Photos'],
    authorized_rep_allowed: true,
    further_appeal_body: 'Washington State Board of Tax Appeals',
    further_appeal_deadline_rule: '30 days from BAE decision',
    state_appeal_board_name: 'Washington State Board of Tax Appeals',
    state_appeal_board_url: 'https://bta.wa.gov/',
    pro_se_tips: 'STRICT 21-business-day evidence deadline before hearing — submit early. eAppeals portal provides instant document access. Hearing notification comes ~45 days in advance. Contact assessor informally first — many issues resolve without formal appeal.',
    notes: '60-day window from value notice mailing. eAppeals preferred.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },

  // ── WAYNE COUNTY, MI (26163) ───────────────────────────────────────────
  {
    county_fips: '26163',
    appeal_board_name: 'Michigan Tax Tribunal (after mandatory March Board of Review)',
    appeal_board_phone: '(313) 224-3035',
    portal_url: 'https://www.michigan.gov/taxtrib',
    appeal_deadline_rule: 'MUST appeal to local March Board of Review FIRST. Then: Residential to Tax Tribunal by July 31. Commercial/Industrial by May 31.',
    next_appeal_deadline: null,
    assessment_cycle: 'Annual',
    current_tax_year: 2026,
    accepts_online_filing: true,
    accepts_email_filing: false,
    requires_mail_filing: false,
    hearing_typically_required: true,
    hearing_format: 'in_person',
    hearing_duration_minutes: 15,
    virtual_hearing_available: false,
    virtual_hearing_platform: null,
    informal_review_available: true,
    informal_review_notes: 'March Board of Review serves as mandatory first-level informal review. Contact local assessor before BOR meeting for preliminary discussion.',
    filing_fee_cents: 0,
    appeal_form_name: 'Tax Tribunal Petition',
    form_download_url: 'https://www.michigan.gov/taxtrib',
    evidence_requirements: ['Comparable property sales', 'Professional appraisal', 'Income/expense docs (commercial)', 'Property condition evidence'],
    required_documents: ['March Board of Review attendance proof', 'Tribunal petition', 'Comparable sales', 'Photos'],
    authorized_rep_allowed: true,
    further_appeal_body: 'Michigan Tax Tribunal — Entire Tribunal',
    further_appeal_deadline_rule: '21 days from Small Claims decision',
    state_appeal_board_name: 'Michigan Tax Tribunal',
    state_appeal_board_url: 'https://www.michigan.gov/taxtrib',
    pro_se_tips: 'MANDATORY: You MUST attend March Board of Review hearing first — skipping it eliminates all further appeal rights. Residential deadline is July 31 (NOT May 31). Commercial deadline is May 31. Different deadlines by property type is a common trap.',
    notes: 'Missing March BOR hearing = no tribunal appeal rights. Two-tier deadline system by property type.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },

  // ── NASSAU COUNTY, NY (36059) ──────────────────────────────────────────
  {
    county_fips: '36059',
    appeal_board_name: 'Nassau County Assessment Review Commission (ARC)',
    appeal_board_phone: '(516) 571-3214',
    portal_url: null,
    appeal_deadline_rule: 'January 2 through March 2 (extended to March 31 in recent years due to demand)',
    next_appeal_deadline: '2027-03-31',
    assessment_cycle: 'Annual',
    current_tax_year: 2026,
    accepts_online_filing: true,
    accepts_email_filing: false,
    requires_mail_filing: false,
    hearing_typically_required: true,
    hearing_format: 'in_person',
    hearing_duration_minutes: 15,
    virtual_hearing_available: false,
    virtual_hearing_platform: null,
    informal_review_available: true,
    informal_review_notes: 'Contact local assessor for informal review before filing with ARC.',
    filing_fee_cents: 0,
    appeal_form_name: 'ARC Appeal Application',
    form_download_url: null,
    evidence_requirements: ['Comparable property sales (3+)', 'Professional appraisal', 'Market analysis from real estate agent', 'Assessment comparison to similar properties'],
    required_documents: ['ARC form', 'Comparable sales', 'Photos', 'Appraisal'],
    authorized_rep_allowed: true,
    further_appeal_body: 'Small Claims Assessment Review (SCAR)',
    further_appeal_deadline_rule: '30 days from ARC decision',
    state_appeal_board_name: 'NYS Supreme Court — Small Claims Assessment Review',
    state_appeal_board_url: 'https://www.tax.ny.gov/pit/property/contest/grievproced.htm',
    pro_se_tips: 'ARC will NOT increase your assessment — they can only reduce or maintain. Extended deadline to March 31 is current. No filing fee. No attorney required. Valuation date is July 1 of prior year — use sales from that period.',
    notes: 'ARC cannot increase assessment. Deadline frequently extended from March 2 to March 31.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },

  // ── SUFFOLK COUNTY, NY (36103) ─────────────────────────────────────────
  {
    county_fips: '36103',
    appeal_board_name: 'Assessment Review Commission (ARC) / Town Board of Assessment Review',
    appeal_board_phone: '(631) 852-2000',
    portal_url: 'https://www.tax.ny.gov/pit/property/contest/grievproced.htm',
    appeal_deadline_rule: 'Grievance Day: third Tuesday in May (varies by town — 10 separate towns with different dates)',
    next_appeal_deadline: '2026-05-19',
    assessment_cycle: 'Varies by town',
    current_tax_year: 2026,
    accepts_online_filing: false,
    accepts_email_filing: false,
    requires_mail_filing: true,
    hearing_typically_required: true,
    hearing_format: 'in_person',
    hearing_duration_minutes: 15,
    virtual_hearing_available: false,
    virtual_hearing_platform: null,
    informal_review_available: true,
    informal_review_notes: 'Contact local town assessor for informal discussion before filing. Each of 10 towns has separate procedures.',
    filing_fee_cents: 0,
    appeal_form_name: 'Form RP-524 (Complaint on Real Property Assessment)',
    form_download_url: 'https://www.tax.ny.gov/pdf/publications/orpts/grievancebooklet.pdf',
    evidence_requirements: ['Comparable property sales (3+)', 'Professional appraisal', 'Market analysis', 'Property condition documentation'],
    required_documents: ['Form RP-524', 'Comparable sales', 'Photos', 'Appraisal (recommended)'],
    authorized_rep_allowed: true,
    further_appeal_body: 'Small Claims Assessment Review (SCAR)',
    further_appeal_deadline_rule: '30 days from BAR decision',
    state_appeal_board_name: 'NYS Supreme Court — Small Claims Assessment Review',
    state_appeal_board_url: 'https://www.tax.ny.gov/pit/property/contest/grievproced.htm',
    pro_se_tips: 'CRITICAL: Suffolk has 10 separate towns each with different filing dates. Check YOUR town assessor for exact Grievance Day. Strict deadline enforcement — no extensions. Valuation date is July 1 of prior year.',
    notes: '10 separate towns with different procedures and dates. Must file with town assessor, not county.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },

  // ── ALLEGHENY COUNTY, PA (42003) ───────────────────────────────────────
  {
    county_fips: '42003',
    appeal_board_name: 'Board of Property Assessment Appeals and Review (BPAAR)',
    appeal_board_phone: '(412) 350-4636',
    portal_url: 'https://www.alleghenycounty.us/Services/Property-Assessments-and-Real-Estate/Appeals',
    appeal_deadline_rule: 'July 1 through September 1 — file year BEFORE tax year applies',
    next_appeal_deadline: '2026-09-01',
    assessment_cycle: 'Varies (some areas not reassessed in decades)',
    current_tax_year: 2026,
    accepts_online_filing: true,
    accepts_email_filing: false,
    requires_mail_filing: false,
    hearing_typically_required: true,
    hearing_format: 'in_person',
    hearing_duration_minutes: 15,
    virtual_hearing_available: false,
    virtual_hearing_platform: null,
    informal_review_available: true,
    informal_review_notes: 'Contact Allegheny County Assessor for informal review before filing.',
    filing_fee_cents: 0,
    appeal_form_name: 'BPAAR Appeal Form',
    form_download_url: 'https://alleghenycontroller.com/property-appeal-guide/',
    evidence_requirements: ['Comparable sales (ACTUAL sales, NOT assessed values)', 'Professional appraisal', 'Property photographs', 'Repair/renovation cost estimates'],
    required_documents: ['BPAAR form', 'Comparable sales evidence', 'Photos', 'Evidence received 10 days before hearing'],
    authorized_rep_allowed: true,
    further_appeal_body: 'Board of Viewers (BOV)',
    further_appeal_deadline_rule: '30 days from BPAAR decision',
    state_appeal_board_name: null,
    state_appeal_board_url: null,
    pro_se_tips: 'Comparable sales must be ACTUAL sales — NOT assessed values. Evidence must be received 10 days before hearing. One postponement allowed per party. File year BEFORE tax year applies — this is a common trap. Second-level Board of Viewers appeal costs $135.25.',
    notes: 'BPAAR free. Board of Viewers $135.25. File year before tax year.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },

  // ── HENNEPIN COUNTY, MN (27053) ────────────────────────────────────────
  {
    county_fips: '27053',
    appeal_board_name: 'Minnesota Tax Court (after Local Board of Appeal and Equalization)',
    appeal_board_phone: '(612) 348-3011',
    portal_url: 'https://mn.gov/tax-court/forms/forms/',
    appeal_deadline_rule: 'ABSOLUTE deadline: April 30 (Minnesota Statute §278.01). No extensions ever.',
    next_appeal_deadline: '2026-04-30',
    assessment_cycle: 'Annual',
    current_tax_year: 2026,
    accepts_online_filing: false,
    accepts_email_filing: false,
    requires_mail_filing: true,
    hearing_typically_required: true,
    hearing_format: 'in_person',
    hearing_duration_minutes: 30,
    virtual_hearing_available: false,
    virtual_hearing_platform: null,
    informal_review_available: true,
    informal_review_notes: 'Multi-level: Contact local assessor first → Local Board of Appeal and Equalization (LBAE) → County Board → Tax Court. Informal contact with assessor strongly encouraged as first step.',
    filing_fee_cents: 0,
    appeal_form_name: 'Tax Court Petition',
    form_download_url: 'https://mn.gov/tax-court/forms/forms/',
    evidence_requirements: ['Comparable property sales', 'Professional appraisal', 'Property condition documentation', 'Market analysis'],
    required_documents: ['Tax Court petition', 'Comparable sales', 'Photos', 'Appraisal'],
    authorized_rep_allowed: true,
    further_appeal_body: 'Minnesota Tax Court — Regular Division',
    further_appeal_deadline_rule: '60 days from Small Claims decision',
    state_appeal_board_name: 'Minnesota Tax Court',
    state_appeal_board_url: 'https://mn.gov/tax-court/',
    pro_se_tips: 'April 30 is ABSOLUTE — no extensions ever (state statute). If April 30 falls on weekend, extends to Monday. Multi-level system required: assessor → LBAE → County Board → Tax Court. Filing location: Court Tower, 300 S. Sixth St., Minneapolis. Hours: Mon-Fri 8:00 AM–4:30 PM.',
    notes: 'April 30 statutory deadline. Court Tower filing location.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },

  // ── DuPAGE COUNTY, IL (17043) ─────────────────────────────────────────
  {
    county_fips: '17043',
    appeal_board_name: 'DuPage County Board of Review',
    appeal_board_phone: '(630) 407-5858',
    portal_url: 'https://www.dupagecounty.gov/government/departments/supervisor_of_assessments/appeal_process.php',
    appeal_deadline_rule: '30 days from date of publication in local newspaper — varies by township (11 townships)',
    next_appeal_deadline: null,
    assessment_cycle: 'Quadrennial',
    current_tax_year: 2025,
    accepts_online_filing: true,
    accepts_email_filing: false,
    requires_mail_filing: false,
    hearing_typically_required: false,
    hearing_format: 'written_only',
    hearing_duration_minutes: null,
    virtual_hearing_available: false,
    virtual_hearing_platform: null,
    informal_review_available: true,
    informal_review_notes: 'Local township assessor informal review encouraged before filing formal appeal with Board of Review.',
    filing_fee_cents: 0,
    appeal_form_name: 'Board of Review Complaint Form',
    form_download_url: 'https://www.dupagecounty.gov/government/departments/supervisor_of_assessments/appeal_process.php',
    evidence_requirements: ['Comparable sales', 'Professional appraisal', 'Property condition documentation', 'Photos'],
    required_documents: ['Complaint form', 'Comparable sales', 'Photos', 'Appraisal (if available)'],
    authorized_rep_allowed: true,
    further_appeal_body: 'Illinois Property Tax Appeal Board (PTAB)',
    further_appeal_deadline_rule: '30 days from Board of Review decision postmark',
    state_appeal_board_name: 'Illinois Property Tax Appeal Board (PTAB)',
    state_appeal_board_url: 'https://www.ptab.illinois.gov/efile/',
    pro_se_tips: '11 townships with different publication dates and deadlines. Deadline tied to newspaper publication date — varies yearly. Check your assessment notice for exact deadline. Board office: 421 N. County Farm Road, Wheaton, IL 60187.',
    notes: '11 separate townships like Cook County. Publication-based deadlines.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },

  // ── LAKE COUNTY, IL (17097) ────────────────────────────────────────────
  {
    county_fips: '17097',
    appeal_board_name: 'Lake County Board of Review',
    appeal_board_phone: '(847) 377-2323',
    portal_url: 'https://www.lakecountyil.gov/551/Online-Appeal-Filing',
    appeal_deadline_rule: '30 days from publication date (check assessment notice for exact deadline)',
    next_appeal_deadline: null,
    assessment_cycle: 'Quadrennial',
    current_tax_year: 2025,
    accepts_online_filing: true,
    accepts_email_filing: false,
    requires_mail_filing: false,
    hearing_typically_required: false,
    hearing_format: 'written_only',
    hearing_duration_minutes: null,
    virtual_hearing_available: false,
    virtual_hearing_platform: null,
    informal_review_available: true,
    informal_review_notes: 'Local township assessor encourages informal contact before formal appeal. Meet with assessor to discuss evidence.',
    filing_fee_cents: 0,
    appeal_form_name: 'SmartFile E-Filing Application',
    form_download_url: 'https://www.lakecountyil.gov/551/Online-Appeal-Filing',
    evidence_requirements: ['Comparable sales', 'Professional appraisal', 'Property condition documentation', 'Assessment comparisons'],
    required_documents: ['SmartFile application', 'Comparable sales', 'Photos', 'Market analysis'],
    authorized_rep_allowed: true,
    further_appeal_body: 'Illinois Property Tax Appeal Board (PTAB)',
    further_appeal_deadline_rule: '30 days from Board of Review decision postmark',
    state_appeal_board_name: 'Illinois Property Tax Appeal Board (PTAB)',
    state_appeal_board_url: 'https://www.ptab.illinois.gov/efile/',
    pro_se_tips: 'E-filing via SmartFile is preferred and available. 30-day deadline from publication date. Meet with township assessor first — many issues resolve informally.',
    notes: 'SmartFile e-filing system. Multiple townships with varying procedures.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },

  // ── WILL COUNTY, IL (17197) ────────────────────────────────────────────
  {
    county_fips: '17197',
    appeal_board_name: 'Will County Board of Review',
    appeal_board_phone: '(815) 740-4648',
    portal_url: 'https://borappeals.willcountysoa.com/',
    appeal_deadline_rule: '30 days from date assessments published in newspaper',
    next_appeal_deadline: null,
    assessment_cycle: 'Quadrennial',
    current_tax_year: 2025,
    accepts_online_filing: true,
    accepts_email_filing: false,
    requires_mail_filing: false,
    hearing_typically_required: false,
    hearing_format: 'written_only',
    hearing_duration_minutes: null,
    virtual_hearing_available: false,
    virtual_hearing_platform: null,
    informal_review_available: true,
    informal_review_notes: 'Contact Will County Board of Review for informal conference. Local assessor review encouraged.',
    filing_fee_cents: 0,
    appeal_form_name: 'Online Complaint Form',
    form_download_url: 'https://borappeals.willcountysoa.com/',
    evidence_requirements: ['Comparable sales', 'Professional appraisal', 'Property condition documentation', 'Market analysis'],
    required_documents: ['Complaint form', 'Comparable sales', 'Photos', 'Assessment comparisons'],
    authorized_rep_allowed: true,
    further_appeal_body: 'Illinois Property Tax Appeal Board (PTAB)',
    further_appeal_deadline_rule: '30 days from Board of Review decision postmark',
    state_appeal_board_name: 'Illinois Property Tax Appeal Board (PTAB)',
    state_appeal_board_url: 'https://www.ptab.illinois.gov/efile/',
    pro_se_tips: '30-day deadline from newspaper publication. Online complaint portal available. Strict deadline enforcement. File early.',
    notes: 'Publication-based deadline varies yearly.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },

  // ── BROWARD COUNTY, FL (12011) ─────────────────────────────────────────
  {
    county_fips: '12011',
    appeal_board_name: 'Broward County Value Adjustment Board (VAB)',
    appeal_board_phone: '(954) 831-4000',
    portal_url: 'https://bcvab.broward.org/AxiaWeb2023/',
    appeal_deadline_rule: '25 days from TRIM notice mailing date (typically mid-August). NO deadline extensions.',
    next_appeal_deadline: null,
    assessment_cycle: 'Annual',
    current_tax_year: 2026,
    accepts_online_filing: true,
    accepts_email_filing: false,
    requires_mail_filing: false,
    hearing_typically_required: true,
    hearing_format: 'in_person',
    hearing_duration_minutes: 15,
    virtual_hearing_available: false,
    virtual_hearing_platform: null,
    informal_review_available: true,
    informal_review_notes: 'Contact Broward County Property Appraiser for informal review after TRIM notice. File petition BEFORE negotiating — deadline is firm.',
    filing_fee_cents: 1500,
    appeal_form_name: 'VAB Petition Form',
    form_download_url: 'https://www.broward.org/VAB/Pages/FilingAPetition.aspx',
    evidence_requirements: ['Comparable property sales', 'Professional appraisal', 'Property condition documentation', 'Market analysis'],
    required_documents: ['VAB Petition', 'Comparable sales', 'Photos', 'Appraisal (recommended)'],
    authorized_rep_allowed: true,
    further_appeal_body: 'Circuit Court',
    further_appeal_deadline_rule: '60 days from VAB decision',
    state_appeal_board_name: null,
    state_appeal_board_url: null,
    pro_se_tips: 'TRIM mails mid-August. 25-day firm deadline. $15 filing fee per parcel. Special Magistrates conduct hearings. File petition BEFORE negotiating informally — deadline does NOT pause.',
    notes: '$15/parcel fee. Petitions rejected if postmarked after deadline.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },

  // ── PALM BEACH COUNTY, FL (12099) ──────────────────────────────────────
  {
    county_fips: '12099',
    appeal_board_name: 'Palm Beach County Value Adjustment Board (VAB)',
    appeal_board_phone: '(561) 355-2866',
    portal_url: 'https://pbcpao.gov/file-petition.htm',
    appeal_deadline_rule: 'Value appeals: 25 days from TRIM notice. Exemption appeals: 30 days from denial notice.',
    next_appeal_deadline: null,
    assessment_cycle: 'Annual',
    current_tax_year: 2026,
    accepts_online_filing: true,
    accepts_email_filing: false,
    requires_mail_filing: false,
    hearing_typically_required: true,
    hearing_format: 'in_person',
    hearing_duration_minutes: 15,
    virtual_hearing_available: false,
    virtual_hearing_platform: null,
    informal_review_available: true,
    informal_review_notes: 'Contact Property Appraiser before formal filing. Negotiation possible but does NOT extend deadline.',
    filing_fee_cents: 1500,
    appeal_form_name: 'VAB Petition Form',
    form_download_url: 'https://pbcpao.gov/file-petition.htm',
    evidence_requirements: ['Comparable property sales', 'Professional appraisal', 'Property condition documentation', 'Market analysis'],
    required_documents: ['VAB Petition', 'Comparable sales', 'Photos', 'Assessment documentation'],
    authorized_rep_allowed: true,
    further_appeal_body: 'Circuit Court',
    further_appeal_deadline_rule: '60 days from VAB decision',
    state_appeal_board_name: null,
    state_appeal_board_url: null,
    pro_se_tips: 'Two different deadlines: 25 days (value) vs 30 days (exemption). Deadlines are FIRM even during informal negotiations. File FIRST, negotiate second. Special Magistrates conduct hearings.',
    notes: '$15/parcel fee. Two different deadline types.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },

  // ── HILLSBOROUGH COUNTY, FL (12057) ────────────────────────────────────
  {
    county_fips: '12057',
    appeal_board_name: 'Hillsborough County Value Adjustment Board (VAB)',
    appeal_board_phone: '(813) 272-6100',
    portal_url: 'https://www.hcpafl.org/',
    appeal_deadline_rule: '25 days from TRIM notice mailing date (typically mid-August). Firm, non-extendable.',
    next_appeal_deadline: null,
    assessment_cycle: 'Annual',
    current_tax_year: 2026,
    accepts_online_filing: true,
    accepts_email_filing: false,
    requires_mail_filing: false,
    hearing_typically_required: true,
    hearing_format: 'in_person',
    hearing_duration_minutes: 15,
    virtual_hearing_available: false,
    virtual_hearing_platform: null,
    informal_review_available: true,
    informal_review_notes: 'Contact Property Appraiser at (813) 272-6100 before formal appeal.',
    filing_fee_cents: 1500,
    appeal_form_name: 'VAB Petition Form',
    form_download_url: 'https://www.hcpafl.org/',
    evidence_requirements: ['Comparable property sales', 'Professional appraisal', 'Property condition documentation', 'Market analysis'],
    required_documents: ['VAB Petition', 'Comparable sales', 'Photos', 'Appraisal (recommended)'],
    authorized_rep_allowed: true,
    further_appeal_body: 'Circuit Court',
    further_appeal_deadline_rule: '60 days from VAB decision',
    state_appeal_board_name: null,
    state_appeal_board_url: null,
    pro_se_tips: 'TRIM notice issued mid-August annually. 25-day firm deadline from mail date. VAB conducts formal hearings with Special Magistrates.',
    notes: '$15/parcel fee. TRIM-based deadline.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },

  // ── CLARK COUNTY, NV (32003) ───────────────────────────────────────────
  {
    county_fips: '32003',
    appeal_board_name: 'Clark County Board of Equalization',
    appeal_board_phone: '(702) 455-4997',
    portal_url: 'https://www.clarkcountynv.gov/government/assessor/real-property',
    appeal_deadline_rule: 'January 15 annually. Assessment notices mailed ~December 15. Only 30-day window.',
    next_appeal_deadline: '2027-01-15',
    assessment_cycle: 'Annual',
    current_tax_year: 2026,
    accepts_online_filing: false,
    accepts_email_filing: false,
    requires_mail_filing: true,
    hearing_typically_required: true,
    hearing_format: 'in_person',
    hearing_duration_minutes: 15,
    virtual_hearing_available: false,
    virtual_hearing_platform: null,
    informal_review_available: true,
    informal_review_notes: 'Contact Assessor at (702) 455-4997 for informal discussion before filing.',
    filing_fee_cents: 0,
    appeal_form_name: 'Appeal Form (obtain from Assessor)',
    form_download_url: 'https://www.clarkcountynv.gov/government/assessor/',
    evidence_requirements: ['Property valuation documentation', 'Comparable property information', 'Market analysis', 'Professional appraisal'],
    required_documents: ['Appeal form', 'Comparable sales', 'Photos', 'Valuation evidence'],
    authorized_rep_allowed: true,
    further_appeal_body: 'Nevada State Board of Equalization',
    further_appeal_deadline_rule: 'Within appeal period after County Board decision',
    state_appeal_board_name: 'Nevada State Board of Equalization',
    state_appeal_board_url: null,
    pro_se_tips: 'STRICT January 15 deadline — single annual deadline. Notices mail ~December 15 giving only 30 days. Phone (702) 455-4997 to request appeal form. Three-level system: County Board → State Board → District Court.',
    notes: 'Shortest appeal window of any major county. December 15 → January 15.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },

  // ── FRANKLIN COUNTY, OH (39049) ────────────────────────────────────────
  {
    county_fips: '39049',
    appeal_board_name: 'Franklin County Board of Revision',
    appeal_board_phone: '(614) 525-3913',
    portal_url: 'https://franklincountyauditor.com/real-estate/board-of-revision',
    appeal_deadline_rule: 'October 30 through March 31. Strict March 31 deadline (no exceptions).',
    next_appeal_deadline: '2027-03-31',
    assessment_cycle: 'Sexennial (6-year reappraisal) with triennial updates',
    current_tax_year: 2025,
    accepts_online_filing: true,
    accepts_email_filing: false,
    requires_mail_filing: false,
    hearing_typically_required: true,
    hearing_format: 'in_person',
    hearing_duration_minutes: 15,
    virtual_hearing_available: false,
    virtual_hearing_platform: null,
    informal_review_available: true,
    informal_review_notes: 'Contact Board of Revision at (614) 525-3913 for informal conference. Assessor informal review also available.',
    filing_fee_cents: 0,
    appeal_form_name: 'Form DTE 1 (Complaint Form)',
    form_download_url: 'https://franklincountyauditor.com/real-estate/board-of-revision',
    evidence_requirements: ['Comparable property sales', 'Professional appraisal', 'Property condition documentation', 'Market analysis'],
    required_documents: ['Form DTE 1', 'Comparable sales', 'Photos', 'Appraisal'],
    authorized_rep_allowed: true,
    further_appeal_body: 'Ohio Board of Tax Appeals',
    further_appeal_deadline_rule: '30 days from Board of Revision decision',
    state_appeal_board_name: 'Ohio Board of Tax Appeals',
    state_appeal_board_url: null,
    pro_se_tips: '5-month filing window (Oct 30–Mar 31) is generous but March 31 is absolute. 40% of filers receive value adjustments. Hand-deliver if filing near deadline. Form DTE 1 is the standard complaint form. File early to avoid volume-related delays.',
    notes: '40% adjustment rate. 5-month filing window.',
    last_verified_date: '2026-03-27',
    verified_by: 'Resourceful Research',
  },
];

async function seedTopCounties() {
  const supabaseUrl = process.env.SUPABASE_URL;
  const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

  if (!supabaseUrl || !supabaseKey) {
    console.error('Error: SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY are required');
    process.exit(1);
  }

  const { createClient } = await import('@supabase/supabase-js');
  const supabase = createClient(supabaseUrl, supabaseKey);

  console.log(`Seeding intelligence for ${TOP_COUNTIES.length} top counties...`);

  let updated = 0;
  let errors = 0;

  for (const county of TOP_COUNTIES) {
    const { county_fips, ...updateData } = county;

    const { error } = await supabase
      .from('county_rules')
      .update(updateData as never)
      .eq('county_fips', county_fips);

    if (error) {
      console.error(`  FAILED ${county_fips}: ${error.message}`);
      errors++;
    } else {
      updated++;
      console.log(`  Updated ${county_fips}`);
    }
  }

  console.log(`\nDone! Updated ${updated} counties. Errors: ${errors}`);
}

seedTopCounties().catch((err) => {
  console.error('Fatal error:', err);
  process.exit(1);
});
