#!/usr/bin/env bash
# ─── Resourceful Local Development Setup ──────────────────────────────────────
# Run this once to set up your local Supabase instance with all migrations,
# seed data (founder admin account), and .env.local configuration.
#
# Prerequisites:
#   - Docker Desktop running
#   - Node.js 18+ installed
#   - pnpm installed
#
# Usage:
#   chmod +x scripts/setup-local.sh
#   ./scripts/setup-local.sh
# ─────────────────────────────────────────────────────────────────────────────

set -euo pipefail

echo ""
echo "╔══════════════════════════════════════════════════╗"
echo "║     Resourceful — Local Development Setup       ║"
echo "╚══════════════════════════════════════════════════╝"
echo ""

# ── Check prerequisites ─────────────────────────────────────────────────────
if ! command -v docker &> /dev/null; then
  echo "ERROR: Docker is not installed. Install Docker Desktop first."
  echo "  https://docs.docker.com/desktop/"
  exit 1
fi

if ! docker info &> /dev/null 2>&1; then
  echo "ERROR: Docker daemon is not running. Start Docker Desktop first."
  exit 1
fi

if ! command -v npx &> /dev/null; then
  echo "ERROR: Node.js/npx not found. Install Node.js 18+ first."
  exit 1
fi

echo "[1/6] Starting Supabase local services..."
echo "       (First run pulls ~2GB of Docker images — be patient)"
echo ""
npx supabase start

echo ""
echo "[2/6] Extracting Supabase credentials..."

# Parse the status output for credentials
SUPABASE_URL=$(npx supabase status --output json 2>/dev/null | node -e "
  const data = JSON.parse(require('fs').readFileSync('/dev/stdin','utf8'));
  console.log(data.API_URL || 'http://127.0.0.1:54321');
" 2>/dev/null || echo "http://127.0.0.1:54321")

ANON_KEY=$(npx supabase status --output json 2>/dev/null | node -e "
  const data = JSON.parse(require('fs').readFileSync('/dev/stdin','utf8'));
  console.log(data.ANON_KEY || '');
" 2>/dev/null || echo "")

SERVICE_ROLE_KEY=$(npx supabase status --output json 2>/dev/null | node -e "
  const data = JSON.parse(require('fs').readFileSync('/dev/stdin','utf8'));
  console.log(data.SERVICE_ROLE_KEY || '');
" 2>/dev/null || echo "")

if [ -z "$ANON_KEY" ] || [ -z "$SERVICE_ROLE_KEY" ]; then
  echo "WARNING: Could not auto-extract keys. Run 'npx supabase status' to get them."
  echo "         Then manually update .env.local"
  ANON_KEY="PASTE_ANON_KEY_HERE"
  SERVICE_ROLE_KEY="PASTE_SERVICE_ROLE_KEY_HERE"
fi

echo "  API URL:          $SUPABASE_URL"
echo "  Anon Key:         ${ANON_KEY:0:20}..."
echo "  Service Role Key: ${SERVICE_ROLE_KEY:0:20}..."

echo ""
echo "[3/6] Creating .env.local..."

cat > .env.local << ENVEOF
# ── Auto-generated by scripts/setup-local.sh ──────────────────────────────
# Local Supabase credentials (safe for development only)

# ---- AI --------------------------------------------------
ANTHROPIC_API_KEY=
AI_MODEL_PRIMARY=claude-sonnet-4-6
AI_MODEL_FAST=claude-haiku-4-5-20251001

# ---- Supabase (local) ------------------------------------
NEXT_PUBLIC_SUPABASE_URL=${SUPABASE_URL}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${ANON_KEY}
SUPABASE_SERVICE_ROLE_KEY=${SERVICE_ROLE_KEY}
SUPABASE_PROJECT_REF=local

# ---- Google APIs (leave blank to skip maps) ---------------
NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=
GOOGLE_MAPS_SERVER_KEY=

# ---- ATTOM (leave blank to use mock data) -----------------
ATTOM_API_KEY=

# ---- Stripe (use test keys from dashboard.stripe.com) -----
NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=
STRIPE_SECRET_KEY=
STRIPE_WEBHOOK_SECRET=

# ---- Resend Email (leave blank to skip email delivery) ----
RESEND_API_KEY=
RESEND_FROM_ADDRESS=reports@localhost
ADMIN_NOTIFICATION_EMAIL=mikelaurenzo7@gmail.com

# ---- App -------------------------------------------------
NEXT_PUBLIC_APP_URL=http://localhost:3000
NODE_ENV=development
ENVEOF

echo "  Created .env.local with local Supabase credentials"

echo ""
echo "[4/6] Running database migrations + seed data..."
npx supabase db reset

echo ""
echo "[5/6] Installing dependencies..."
pnpm install

echo ""
echo "[6/6] Setup complete!"
echo ""
echo "╔══════════════════════════════════════════════════╗"
echo "║              Ready to develop!                  ║"
echo "╠══════════════════════════════════════════════════╣"
echo "║                                                 ║"
echo "║  Start dev server:   pnpm dev                   ║"
echo "║  App:                http://localhost:3000       ║"
echo "║  Admin:              http://localhost:3000/admin ║"
echo "║  Supabase Studio:    http://localhost:54323      ║"
echo "║  Email inbox:        http://localhost:54324      ║"
echo "║                                                 ║"
echo "║  Admin login:                                   ║"
echo "║    Email:    mikelaurenzo7@gmail.com             ║"
echo "║    Password: Resourceful2026!                   ║"
echo "║                                                 ║"
echo "║  Founder account (skips payment):               ║"
echo "║    Use mikelaurenzo7@gmail.com at checkout      ║"
echo "║                                                 ║"
echo "║  To seed counties (optional, needs internet):   ║"
echo "║    SUPABASE_URL=${SUPABASE_URL}                 ║"
echo "║    npx tsx scripts/seed-counties.ts             ║"
echo "║                                                 ║"
echo "╚══════════════════════════════════════════════════╝"
echo ""
