// ─── State-Level Assessment Rules ────────────────────────────────────────────
// Default assessment ratios, appeal board info, and filing rules by state.
// These are state-level defaults applied to every county in that state during
// seeding. County-specific overrides can be made via the admin UI afterward.
//
// Sources: IAAO assessment ratio surveys, state statutes, state department of
// revenue websites. These are the STANDARD ratios — some counties within a
// state may deviate (e.g., IL counties use different assessment levels).
//
// assessment_ratio: The ratio of assessed value to market value.
//   - 1.000 = full market value (TX, CA, FL, etc.)
//   - 0.333 = 33.3% of market value (IL Cook County residential)
//   - 0.100 = 10% of market value (some states)

export interface StateRules {
  assessment_ratio_residential: number;
  assessment_ratio_commercial: number;
  assessment_ratio_industrial: number;
  assessment_methodology: string;
  appeal_board_name: string;
  appeal_deadline_rule: string;
  hearing_typically_required: boolean;
  accepts_online_filing: boolean;
  accepts_email_filing: boolean;
  requires_mail_filing: boolean;
  assessment_cycle: string;
  authorized_rep_allowed: boolean;
}

export const STATE_RULES: Record<string, StateRules> = {
  AL: {
    assessment_ratio_residential: 0.100,
    assessment_ratio_commercial: 0.200,
    assessment_ratio_industrial: 0.200,
    assessment_methodology: 'Fractional assessment — residential at 10%, commercial/industrial at 20% of fair market value',
    appeal_board_name: 'County Board of Equalization',
    appeal_deadline_rule: 'Within 30 days of assessment notice or by third Monday in May',
    hearing_typically_required: true,
    accepts_online_filing: false,
    accepts_email_filing: false,
    requires_mail_filing: true,
    assessment_cycle: 'Annual',
    authorized_rep_allowed: true,
  },
  AK: {
    assessment_ratio_residential: 1.000,
    assessment_ratio_commercial: 1.000,
    assessment_ratio_industrial: 1.000,
    assessment_methodology: 'Full market value assessment',
    appeal_board_name: 'Board of Equalization',
    appeal_deadline_rule: 'Within 30 days of assessment notice',
    hearing_typically_required: true,
    accepts_online_filing: false,
    accepts_email_filing: false,
    requires_mail_filing: true,
    assessment_cycle: 'Annual',
    authorized_rep_allowed: true,
  },
  AZ: {
    assessment_ratio_residential: 0.100,
    assessment_ratio_commercial: 0.180,
    assessment_ratio_industrial: 0.180,
    assessment_methodology: 'Fractional assessment — residential at 10%, commercial at 18% of full cash value',
    appeal_board_name: 'County Assessor / State Board of Equalization',
    appeal_deadline_rule: 'File petition by December 15 for the following tax year or within 60 days of notice of value',
    hearing_typically_required: true,
    accepts_online_filing: true,
    accepts_email_filing: false,
    requires_mail_filing: false,
    assessment_cycle: 'Annual',
    authorized_rep_allowed: true,
  },
  AR: {
    assessment_ratio_residential: 0.200,
    assessment_ratio_commercial: 0.200,
    assessment_ratio_industrial: 0.200,
    assessment_methodology: 'Fractional assessment at 20% of market value',
    appeal_board_name: 'County Equalization Board',
    appeal_deadline_rule: 'Third Monday in August through the third Monday in September',
    hearing_typically_required: true,
    accepts_online_filing: false,
    accepts_email_filing: false,
    requires_mail_filing: true,
    assessment_cycle: 'Annual',
    authorized_rep_allowed: true,
  },
  CA: {
    assessment_ratio_residential: 1.000,
    assessment_ratio_commercial: 1.000,
    assessment_ratio_industrial: 1.000,
    assessment_methodology: 'Full market value (Proposition 13 — base year value with max 2% annual increase)',
    appeal_board_name: 'Assessment Appeals Board',
    appeal_deadline_rule: 'July 2 through September 15 (or November 30 in some counties)',
    hearing_typically_required: true,
    accepts_online_filing: true,
    accepts_email_filing: false,
    requires_mail_filing: false,
    assessment_cycle: 'Annual (Prop 13 base year)',
    authorized_rep_allowed: true,
  },
  CO: {
    assessment_ratio_residential: 0.068,
    assessment_ratio_commercial: 0.290,
    assessment_ratio_industrial: 0.290,
    assessment_methodology: 'Fractional assessment — residential at 6.8%, commercial/industrial at 29% of actual value',
    appeal_board_name: 'County Board of Equalization',
    appeal_deadline_rule: 'May 1 through June 1 (odd years for real property)',
    hearing_typically_required: true,
    accepts_online_filing: true,
    accepts_email_filing: false,
    requires_mail_filing: false,
    assessment_cycle: 'Biennial (odd years)',
    authorized_rep_allowed: true,
  },
  CT: {
    assessment_ratio_residential: 0.700,
    assessment_ratio_commercial: 0.700,
    assessment_ratio_industrial: 0.700,
    assessment_methodology: 'Assessment at 70% of fair market value',
    appeal_board_name: 'Board of Assessment Appeals',
    appeal_deadline_rule: 'February 20 (or by petition to Superior Court by April 15)',
    hearing_typically_required: true,
    accepts_online_filing: false,
    accepts_email_filing: false,
    requires_mail_filing: true,
    assessment_cycle: 'Every 5 years (revaluation)',
    authorized_rep_allowed: true,
  },
  DE: {
    assessment_ratio_residential: 1.000,
    assessment_ratio_commercial: 1.000,
    assessment_ratio_industrial: 1.000,
    assessment_methodology: 'Full value assessment (based on older base years in most counties)',
    appeal_board_name: 'Board of Assessment Review',
    appeal_deadline_rule: 'Varies by county — typically April or upon receipt of assessment notice',
    hearing_typically_required: true,
    accepts_online_filing: false,
    accepts_email_filing: false,
    requires_mail_filing: true,
    assessment_cycle: 'Varies by county',
    authorized_rep_allowed: true,
  },
  DC: {
    assessment_ratio_residential: 1.000,
    assessment_ratio_commercial: 1.000,
    assessment_ratio_industrial: 1.000,
    assessment_methodology: 'Full market value assessment',
    appeal_board_name: 'DC Real Property Tax Appeals Commission',
    appeal_deadline_rule: 'April 1 of the tax year',
    hearing_typically_required: true,
    accepts_online_filing: true,
    accepts_email_filing: false,
    requires_mail_filing: false,
    assessment_cycle: 'Annual',
    authorized_rep_allowed: true,
  },
  FL: {
    assessment_ratio_residential: 1.000,
    assessment_ratio_commercial: 1.000,
    assessment_ratio_industrial: 1.000,
    assessment_methodology: 'Full market value (with Save Our Homes 3% cap for homestead)',
    appeal_board_name: 'Value Adjustment Board (VAB)',
    appeal_deadline_rule: 'Within 25 days of TRIM notice (typically September)',
    hearing_typically_required: true,
    accepts_online_filing: true,
    accepts_email_filing: false,
    requires_mail_filing: false,
    assessment_cycle: 'Annual',
    authorized_rep_allowed: true,
  },
  GA: {
    assessment_ratio_residential: 0.400,
    assessment_ratio_commercial: 0.400,
    assessment_ratio_industrial: 0.400,
    assessment_methodology: 'Assessment at 40% of fair market value',
    appeal_board_name: 'County Board of Tax Assessors / Board of Equalization',
    appeal_deadline_rule: 'Within 45 days of assessment notice',
    hearing_typically_required: true,
    accepts_online_filing: false,
    accepts_email_filing: false,
    requires_mail_filing: true,
    assessment_cycle: 'Annual',
    authorized_rep_allowed: true,
  },
  HI: {
    assessment_ratio_residential: 1.000,
    assessment_ratio_commercial: 1.000,
    assessment_ratio_industrial: 1.000,
    assessment_methodology: 'Full market value assessment',
    appeal_board_name: 'Board of Review / Tax Appeal Court',
    appeal_deadline_rule: 'Within 90 days of assessment date (April 9 for Honolulu)',
    hearing_typically_required: true,
    accepts_online_filing: false,
    accepts_email_filing: false,
    requires_mail_filing: true,
    assessment_cycle: 'Annual',
    authorized_rep_allowed: true,
  },
  ID: {
    assessment_ratio_residential: 1.000,
    assessment_ratio_commercial: 1.000,
    assessment_ratio_industrial: 1.000,
    assessment_methodology: 'Full market value assessment',
    appeal_board_name: 'County Board of Equalization',
    appeal_deadline_rule: 'Fourth Monday in June (or within 30 days of notice)',
    hearing_typically_required: true,
    accepts_online_filing: false,
    accepts_email_filing: false,
    requires_mail_filing: true,
    assessment_cycle: 'Annual',
    authorized_rep_allowed: true,
  },
  IL: {
    assessment_ratio_residential: 0.333,
    assessment_ratio_commercial: 0.333,
    assessment_ratio_industrial: 0.333,
    assessment_methodology: 'Fractional assessment at 33.33% of fair market value (Cook County uses different levels: 10% residential, 25% commercial)',
    appeal_board_name: 'County Board of Review',
    appeal_deadline_rule: '30 days from publication of assessment list (varies by township)',
    hearing_typically_required: false,
    accepts_online_filing: true,
    accepts_email_filing: false,
    requires_mail_filing: false,
    assessment_cycle: 'Quadrennial (4-year cycle, varies by county)',
    authorized_rep_allowed: true,
  },
  IN: {
    assessment_ratio_residential: 1.000,
    assessment_ratio_commercial: 1.000,
    assessment_ratio_industrial: 1.000,
    assessment_methodology: 'Full market value (true tax value) assessment',
    appeal_board_name: 'County Property Tax Assessment Board of Appeals (PTABOA)',
    appeal_deadline_rule: 'June 15 or within 45 days of assessment notice',
    hearing_typically_required: true,
    accepts_online_filing: false,
    accepts_email_filing: false,
    requires_mail_filing: true,
    assessment_cycle: 'Annual (trending)',
    authorized_rep_allowed: true,
  },
  IA: {
    assessment_ratio_residential: 1.000,
    assessment_ratio_commercial: 1.000,
    assessment_ratio_industrial: 1.000,
    assessment_methodology: 'Full market value assessment (with rollback/equalization orders)',
    appeal_board_name: 'County Board of Review',
    appeal_deadline_rule: 'April 2 through April 30',
    hearing_typically_required: true,
    accepts_online_filing: false,
    accepts_email_filing: false,
    requires_mail_filing: true,
    assessment_cycle: 'Biennial (odd years)',
    authorized_rep_allowed: true,
  },
  KS: {
    assessment_ratio_residential: 0.115,
    assessment_ratio_commercial: 0.250,
    assessment_ratio_industrial: 0.250,
    assessment_methodology: 'Fractional assessment — residential at 11.5%, commercial/industrial at 25% of fair market value',
    appeal_board_name: 'County Appraiser / Board of Tax Appeals (BOTA)',
    appeal_deadline_rule: 'March 15 (informal) or within 30 days of informal decision (formal)',
    hearing_typically_required: true,
    accepts_online_filing: false,
    accepts_email_filing: false,
    requires_mail_filing: true,
    assessment_cycle: 'Annual',
    authorized_rep_allowed: true,
  },
  KY: {
    assessment_ratio_residential: 1.000,
    assessment_ratio_commercial: 1.000,
    assessment_ratio_industrial: 1.000,
    assessment_methodology: 'Full fair cash value assessment',
    appeal_board_name: 'County Board of Assessment Appeals',
    appeal_deadline_rule: 'January 1 through January 31 (or within 30 days of assessment)',
    hearing_typically_required: true,
    accepts_online_filing: false,
    accepts_email_filing: false,
    requires_mail_filing: true,
    assessment_cycle: 'Annual',
    authorized_rep_allowed: true,
  },
  LA: {
    assessment_ratio_residential: 0.100,
    assessment_ratio_commercial: 0.150,
    assessment_ratio_industrial: 0.150,
    assessment_methodology: 'Fractional assessment — residential at 10%, commercial at 15% of fair market value',
    appeal_board_name: 'Louisiana Tax Commission / Parish Board of Review',
    appeal_deadline_rule: 'Within 20 calendar days after public notice of assessment rolls (typically August-September)',
    hearing_typically_required: true,
    accepts_online_filing: false,
    accepts_email_filing: false,
    requires_mail_filing: true,
    assessment_cycle: 'Every 4 years',
    authorized_rep_allowed: true,
  },
  ME: {
    assessment_ratio_residential: 1.000,
    assessment_ratio_commercial: 1.000,
    assessment_ratio_industrial: 1.000,
    assessment_methodology: 'Full market value (just value) assessment',
    appeal_board_name: 'Local Board of Assessment Review',
    appeal_deadline_rule: 'April 1 or within 185 days of tax commitment',
    hearing_typically_required: true,
    accepts_online_filing: false,
    accepts_email_filing: false,
    requires_mail_filing: true,
    assessment_cycle: 'Annual',
    authorized_rep_allowed: true,
  },
  MD: {
    assessment_ratio_residential: 1.000,
    assessment_ratio_commercial: 1.000,
    assessment_ratio_industrial: 1.000,
    assessment_methodology: 'Full market value assessment (phased in over 3 years)',
    appeal_board_name: 'Property Tax Assessment Appeal Board',
    appeal_deadline_rule: 'Within 45 days of assessment notice',
    hearing_typically_required: true,
    accepts_online_filing: true,
    accepts_email_filing: false,
    requires_mail_filing: false,
    assessment_cycle: 'Triennial (3-year cycle)',
    authorized_rep_allowed: true,
  },
  MA: {
    assessment_ratio_residential: 1.000,
    assessment_ratio_commercial: 1.000,
    assessment_ratio_industrial: 1.000,
    assessment_methodology: 'Full fair cash value assessment',
    appeal_board_name: 'Board of Assessors / Appellate Tax Board',
    appeal_deadline_rule: 'February 1 (or within 3 months of actual tax bill, whichever is later)',
    hearing_typically_required: true,
    accepts_online_filing: true,
    accepts_email_filing: false,
    requires_mail_filing: false,
    assessment_cycle: 'Annual',
    authorized_rep_allowed: true,
  },
  MI: {
    assessment_ratio_residential: 0.500,
    assessment_ratio_commercial: 0.500,
    assessment_ratio_industrial: 0.500,
    assessment_methodology: 'Assessment at 50% of true cash value (taxable value capped by Proposal A)',
    appeal_board_name: 'Board of Review / Michigan Tax Tribunal',
    appeal_deadline_rule: 'March Board of Review meeting (first or second week of March)',
    hearing_typically_required: true,
    accepts_online_filing: true,
    accepts_email_filing: false,
    requires_mail_filing: false,
    assessment_cycle: 'Annual',
    authorized_rep_allowed: true,
  },
  MN: {
    assessment_ratio_residential: 1.000,
    assessment_ratio_commercial: 1.000,
    assessment_ratio_industrial: 1.000,
    assessment_methodology: 'Full market value assessment (with class rates applied to compute tax capacity)',
    appeal_board_name: 'County Board of Appeal and Equalization / Minnesota Tax Court',
    appeal_deadline_rule: 'Open Book meeting in April, then Board of Appeal and Equalization in June',
    hearing_typically_required: true,
    accepts_online_filing: false,
    accepts_email_filing: false,
    requires_mail_filing: true,
    assessment_cycle: 'Annual',
    authorized_rep_allowed: true,
  },
  MS: {
    assessment_ratio_residential: 0.100,
    assessment_ratio_commercial: 0.150,
    assessment_ratio_industrial: 0.150,
    assessment_methodology: 'Fractional assessment — residential at 10%, commercial/industrial at 15% of true value',
    appeal_board_name: 'County Board of Supervisors',
    appeal_deadline_rule: 'First Monday in April through the first Monday in May',
    hearing_typically_required: true,
    accepts_online_filing: false,
    accepts_email_filing: false,
    requires_mail_filing: true,
    assessment_cycle: 'Every 4 years',
    authorized_rep_allowed: true,
  },
  MO: {
    assessment_ratio_residential: 0.190,
    assessment_ratio_commercial: 0.320,
    assessment_ratio_industrial: 0.320,
    assessment_methodology: 'Fractional assessment — residential at 19%, commercial/industrial at 32% of true value in money',
    appeal_board_name: 'County Board of Equalization / State Tax Commission',
    appeal_deadline_rule: 'Within 30 days of assessment notice (typically June-July in odd years)',
    hearing_typically_required: true,
    accepts_online_filing: false,
    accepts_email_filing: false,
    requires_mail_filing: true,
    assessment_cycle: 'Biennial (odd years)',
    authorized_rep_allowed: true,
  },
  MT: {
    assessment_ratio_residential: 1.000,
    assessment_ratio_commercial: 1.000,
    assessment_ratio_industrial: 1.000,
    assessment_methodology: 'Full market value assessment (with class-specific tax rates)',
    appeal_board_name: 'County Tax Appeal Board / Montana Tax Appeal Board',
    appeal_deadline_rule: 'Within 30 days of assessment notice',
    hearing_typically_required: true,
    accepts_online_filing: false,
    accepts_email_filing: true,
    requires_mail_filing: false,
    assessment_cycle: 'Biennial (reappraisal every 2 years)',
    authorized_rep_allowed: true,
  },
  NE: {
    assessment_ratio_residential: 1.000,
    assessment_ratio_commercial: 1.000,
    assessment_ratio_industrial: 1.000,
    assessment_methodology: 'Full actual value assessment',
    appeal_board_name: 'County Board of Equalization / Tax Equalization and Review Commission (TERC)',
    appeal_deadline_rule: 'June 1 through June 30',
    hearing_typically_required: true,
    accepts_online_filing: false,
    accepts_email_filing: false,
    requires_mail_filing: true,
    assessment_cycle: 'Annual',
    authorized_rep_allowed: true,
  },
  NV: {
    assessment_ratio_residential: 0.350,
    assessment_ratio_commercial: 0.350,
    assessment_ratio_industrial: 0.350,
    assessment_methodology: 'Assessment at 35% of taxable value (full cash value less depreciation)',
    appeal_board_name: 'County Board of Equalization / State Board of Equalization',
    appeal_deadline_rule: 'January 15 through February 28',
    hearing_typically_required: true,
    accepts_online_filing: false,
    accepts_email_filing: false,
    requires_mail_filing: true,
    assessment_cycle: 'Annual',
    authorized_rep_allowed: true,
  },
  NH: {
    assessment_ratio_residential: 1.000,
    assessment_ratio_commercial: 1.000,
    assessment_ratio_industrial: 1.000,
    assessment_methodology: 'Full market value assessment',
    appeal_board_name: 'Board of Tax and Land Appeals (BTLA)',
    appeal_deadline_rule: 'By September 1 or within 120 days of final tax bill',
    hearing_typically_required: true,
    accepts_online_filing: false,
    accepts_email_filing: false,
    requires_mail_filing: true,
    assessment_cycle: 'Every 5 years (municipality-dependent)',
    authorized_rep_allowed: true,
  },
  NJ: {
    assessment_ratio_residential: 1.000,
    assessment_ratio_commercial: 1.000,
    assessment_ratio_industrial: 1.000,
    assessment_methodology: 'Full true value assessment (with equalization ratios varying by municipality)',
    appeal_board_name: 'County Board of Taxation / New Jersey Tax Court',
    appeal_deadline_rule: 'April 1 (January 15 for reassessment/revaluation year)',
    hearing_typically_required: true,
    accepts_online_filing: true,
    accepts_email_filing: false,
    requires_mail_filing: false,
    assessment_cycle: 'Annual',
    authorized_rep_allowed: true,
  },
  NM: {
    assessment_ratio_residential: 0.333,
    assessment_ratio_commercial: 0.333,
    assessment_ratio_industrial: 0.333,
    assessment_methodology: 'Assessment at 33.33% of market value',
    appeal_board_name: 'County Valuation Protest Board',
    appeal_deadline_rule: 'Within 30 days of notice of value (typically March)',
    hearing_typically_required: true,
    accepts_online_filing: false,
    accepts_email_filing: false,
    requires_mail_filing: true,
    assessment_cycle: 'Annual',
    authorized_rep_allowed: true,
  },
  NY: {
    assessment_ratio_residential: 1.000,
    assessment_ratio_commercial: 1.000,
    assessment_ratio_industrial: 1.000,
    assessment_methodology: 'Full market value assessment (varies by municipality — some use fractional)',
    appeal_board_name: 'Board of Assessment Review (BAR)',
    appeal_deadline_rule: 'Grievance Day — typically third Tuesday in May (varies by municipality)',
    hearing_typically_required: true,
    accepts_online_filing: false,
    accepts_email_filing: false,
    requires_mail_filing: true,
    assessment_cycle: 'Varies by municipality',
    authorized_rep_allowed: true,
  },
  NC: {
    assessment_ratio_residential: 1.000,
    assessment_ratio_commercial: 1.000,
    assessment_ratio_industrial: 1.000,
    assessment_methodology: 'Full market value assessment',
    appeal_board_name: 'County Board of Equalization and Review',
    appeal_deadline_rule: 'During the Board of Equalization session (varies by county, typically April-May of revaluation year)',
    hearing_typically_required: true,
    accepts_online_filing: false,
    accepts_email_filing: false,
    requires_mail_filing: true,
    assessment_cycle: 'Every 4-8 years (county-dependent)',
    authorized_rep_allowed: true,
  },
  ND: {
    assessment_ratio_residential: 0.090,
    assessment_ratio_commercial: 0.100,
    assessment_ratio_industrial: 0.100,
    assessment_methodology: 'Fractional assessment — residential at 9%, commercial at 10% of true and full value',
    appeal_board_name: 'City/Township Board of Equalization → County Board of Equalization',
    appeal_deadline_rule: 'April meeting of City/Township Board of Equalization',
    hearing_typically_required: true,
    accepts_online_filing: false,
    accepts_email_filing: false,
    requires_mail_filing: true,
    assessment_cycle: 'Annual',
    authorized_rep_allowed: true,
  },
  OH: {
    assessment_ratio_residential: 0.350,
    assessment_ratio_commercial: 0.350,
    assessment_ratio_industrial: 0.350,
    assessment_methodology: 'Assessment at 35% of true (market) value',
    appeal_board_name: 'County Board of Revision',
    appeal_deadline_rule: 'January 1 through March 31',
    hearing_typically_required: true,
    accepts_online_filing: false,
    accepts_email_filing: false,
    requires_mail_filing: true,
    assessment_cycle: 'Sexennial (6-year reappraisal) with triennial updates',
    authorized_rep_allowed: true,
  },
  OK: {
    assessment_ratio_residential: 0.110,
    assessment_ratio_commercial: 0.110,
    assessment_ratio_industrial: 0.110,
    assessment_methodology: 'Assessment at 11% of fair cash value (residential, commercial, industrial)',
    appeal_board_name: 'County Board of Equalization',
    appeal_deadline_rule: 'Within 30 days of mailing of assessment notice',
    hearing_typically_required: true,
    accepts_online_filing: false,
    accepts_email_filing: false,
    requires_mail_filing: true,
    assessment_cycle: 'Annual',
    authorized_rep_allowed: true,
  },
  OR: {
    assessment_ratio_residential: 1.000,
    assessment_ratio_commercial: 1.000,
    assessment_ratio_industrial: 1.000,
    assessment_methodology: 'Full real market value (taxes based on lesser of RMV or Measure 50 assessed value)',
    appeal_board_name: 'County Board of Property Tax Appeals (BoPTA)',
    appeal_deadline_rule: 'January 1 through December 31 (petition by December 31)',
    hearing_typically_required: true,
    accepts_online_filing: true,
    accepts_email_filing: false,
    requires_mail_filing: false,
    assessment_cycle: 'Annual',
    authorized_rep_allowed: true,
  },
  PA: {
    assessment_ratio_residential: 1.000,
    assessment_ratio_commercial: 1.000,
    assessment_ratio_industrial: 1.000,
    assessment_methodology: 'Full market value assessment (using county-specific common level ratios)',
    appeal_board_name: 'County Board of Assessment Appeals',
    appeal_deadline_rule: 'Varies by county — typically August 1 through October 1',
    hearing_typically_required: true,
    accepts_online_filing: false,
    accepts_email_filing: false,
    requires_mail_filing: true,
    assessment_cycle: 'Varies by county (some not reassessed in decades)',
    authorized_rep_allowed: true,
  },
  RI: {
    assessment_ratio_residential: 1.000,
    assessment_ratio_commercial: 1.000,
    assessment_ratio_industrial: 1.000,
    assessment_methodology: 'Full fair market value assessment',
    appeal_board_name: 'Tax Assessor / City/Town Tax Board of Review',
    appeal_deadline_rule: 'Within 90 days of first tax payment due date under new assessment',
    hearing_typically_required: true,
    accepts_online_filing: false,
    accepts_email_filing: false,
    requires_mail_filing: true,
    assessment_cycle: 'Every 9 years (statistical update every 3 years)',
    authorized_rep_allowed: true,
  },
  SC: {
    assessment_ratio_residential: 0.040,
    assessment_ratio_commercial: 0.060,
    assessment_ratio_industrial: 0.105,
    assessment_methodology: 'Fractional assessment — primary residential at 4%, commercial at 6%, manufacturing at 10.5% of fair market value',
    appeal_board_name: 'County Board of Assessment Appeals',
    appeal_deadline_rule: 'Within 90 days of assessment notice during reassessment year',
    hearing_typically_required: true,
    accepts_online_filing: false,
    accepts_email_filing: false,
    requires_mail_filing: true,
    assessment_cycle: 'Every 5 years (county-dependent)',
    authorized_rep_allowed: true,
  },
  SD: {
    assessment_ratio_residential: 1.000,
    assessment_ratio_commercial: 1.000,
    assessment_ratio_industrial: 1.000,
    assessment_methodology: 'Full market value assessment',
    appeal_board_name: 'County Board of Equalization / Office of Hearing Examiners',
    appeal_deadline_rule: 'First Tuesday in April through the third Tuesday in April',
    hearing_typically_required: true,
    accepts_online_filing: false,
    accepts_email_filing: false,
    requires_mail_filing: true,
    assessment_cycle: 'Annual',
    authorized_rep_allowed: true,
  },
  TN: {
    assessment_ratio_residential: 0.250,
    assessment_ratio_commercial: 0.400,
    assessment_ratio_industrial: 0.400,
    assessment_methodology: 'Fractional assessment — residential at 25%, commercial/industrial at 40% of appraised value',
    appeal_board_name: 'County Board of Equalization / State Board of Equalization',
    appeal_deadline_rule: 'June 1 through the date the County Board of Equalization adjourns (typically June)',
    hearing_typically_required: true,
    accepts_online_filing: false,
    accepts_email_filing: false,
    requires_mail_filing: true,
    assessment_cycle: 'Every 4-6 years (county-dependent)',
    authorized_rep_allowed: true,
  },
  TX: {
    assessment_ratio_residential: 1.000,
    assessment_ratio_commercial: 1.000,
    assessment_ratio_industrial: 1.000,
    assessment_methodology: 'Full market value assessment (with homestead exemptions and 10% annual cap)',
    appeal_board_name: 'Appraisal Review Board (ARB)',
    appeal_deadline_rule: 'May 15 or within 30 days of assessment notice, whichever is later',
    hearing_typically_required: true,
    accepts_online_filing: true,
    accepts_email_filing: false,
    requires_mail_filing: false,
    assessment_cycle: 'Annual',
    authorized_rep_allowed: true,
  },
  UT: {
    assessment_ratio_residential: 0.550,
    assessment_ratio_commercial: 1.000,
    assessment_ratio_industrial: 1.000,
    assessment_methodology: 'Residential at 55% of fair market value; commercial/industrial at 100%',
    appeal_board_name: 'County Board of Equalization',
    appeal_deadline_rule: 'September 15 or within 45 days of assessment notice',
    hearing_typically_required: true,
    accepts_online_filing: false,
    accepts_email_filing: false,
    requires_mail_filing: true,
    assessment_cycle: 'Annual',
    authorized_rep_allowed: true,
  },
  VT: {
    assessment_ratio_residential: 1.000,
    assessment_ratio_commercial: 1.000,
    assessment_ratio_industrial: 1.000,
    assessment_methodology: 'Full fair market value assessment (appraisal value listed; equalization applied)',
    appeal_board_name: 'Board of Civil Authority / State Appraiser',
    appeal_deadline_rule: 'Within 30 days of lodging of grand list (varies by town)',
    hearing_typically_required: true,
    accepts_online_filing: false,
    accepts_email_filing: false,
    requires_mail_filing: true,
    assessment_cycle: 'Varies by town',
    authorized_rep_allowed: true,
  },
  VA: {
    assessment_ratio_residential: 1.000,
    assessment_ratio_commercial: 1.000,
    assessment_ratio_industrial: 1.000,
    assessment_methodology: 'Full fair market value assessment',
    appeal_board_name: 'Board of Equalization / Circuit Court',
    appeal_deadline_rule: 'Varies by locality — typically within assessment equalization period or by application deadline',
    hearing_typically_required: true,
    accepts_online_filing: false,
    accepts_email_filing: false,
    requires_mail_filing: true,
    assessment_cycle: 'Annual or biennial (locality-dependent)',
    authorized_rep_allowed: true,
  },
  WA: {
    assessment_ratio_residential: 1.000,
    assessment_ratio_commercial: 1.000,
    assessment_ratio_industrial: 1.000,
    assessment_methodology: 'Full true and fair value (market value) assessment',
    appeal_board_name: 'County Board of Equalization',
    appeal_deadline_rule: 'Within 60 days of assessment notice (typically July 1 for appeals filed by petition)',
    hearing_typically_required: true,
    accepts_online_filing: false,
    accepts_email_filing: false,
    requires_mail_filing: true,
    assessment_cycle: 'Annual (physical inspection every 4-6 years)',
    authorized_rep_allowed: true,
  },
  WV: {
    assessment_ratio_residential: 0.600,
    assessment_ratio_commercial: 0.600,
    assessment_ratio_industrial: 0.600,
    assessment_methodology: 'Assessment at 60% of appraised value (market value)',
    appeal_board_name: 'County Commission sitting as Board of Review and Equalization',
    appeal_deadline_rule: 'February 1 through February 28',
    hearing_typically_required: true,
    accepts_online_filing: false,
    accepts_email_filing: false,
    requires_mail_filing: true,
    assessment_cycle: 'Annual',
    authorized_rep_allowed: true,
  },
  WI: {
    assessment_ratio_residential: 1.000,
    assessment_ratio_commercial: 1.000,
    assessment_ratio_industrial: 1.000,
    assessment_methodology: 'Full market value assessment',
    appeal_board_name: 'Board of Review',
    appeal_deadline_rule: 'During Board of Review meeting (typically May-June, 48 hours notice required)',
    hearing_typically_required: true,
    accepts_online_filing: false,
    accepts_email_filing: false,
    requires_mail_filing: true,
    assessment_cycle: 'Annual',
    authorized_rep_allowed: true,
  },
  WY: {
    assessment_ratio_residential: 0.096,
    assessment_ratio_commercial: 0.096,
    assessment_ratio_industrial: 0.096,
    assessment_methodology: 'Assessment at 9.5% of fair market value',
    appeal_board_name: 'County Board of Equalization / State Board of Equalization',
    appeal_deadline_rule: 'Within 30 days of assessment notice',
    hearing_typically_required: true,
    accepts_online_filing: false,
    accepts_email_filing: false,
    requires_mail_filing: true,
    assessment_cycle: 'Annual',
    authorized_rep_allowed: true,
  },
};
